export type ItemBaseType =
  | 'Abyssal Axe'
  | 'Abyssal Sceptre'
  | 'Academy Map'
  | 'Accumulator Wand'
  | 'Acid Caverns Map'
  | 'Aetherwind Gloves'
  | 'Agate Amulet'
  | 'Aggregator Charm'
  | 'Alder Spiked Shield'
  | 'Alleyways Map'
  | 'Alloyed Spiked Shield'
  | 'Alternating Sceptre'
  | "Alva's Memory"
  | 'Amber Amulet'
  | 'Ambush Boots'
  | 'Ambush Mitts'
  | 'Ambusher'
  | 'Amethyst Flask'
  | 'Amethyst Ring'
  | 'Anarchic Spiritblade'
  | 'Ancestral Club'
  | 'Ancient City Map'
  | 'Ancient Gauntlets'
  | 'Ancient Greaves'
  | 'Ancient Spirit Shield'
  | 'Ancient Sword'
  | 'Angelic Kite Shield'
  | 'Antique Gauntlets'
  | 'Antique Greaves'
  | 'Antique Rapier'
  | 'Apex Cleaver'
  | 'Apex Rapier'
  | "Apothecary's Gloves"
  | 'Aquamarine Flask'
  | 'Arachnid Nest Map'
  | 'Arachnid Tomb Map'
  | 'Arcade Map'
  | 'Arcanist Gloves'
  | 'Arcanist Slippers'
  | 'Archdemon Crown'
  | 'Archon Kite Shield'
  | 'Archon Kite Shield Piece'
  | 'Arena Map'
  | 'Arena Plate'
  | 'Arid Lake Map'
  | 'Arming Axe'
  | 'Armoury Map'
  | 'Arsenal Map'
  | 'Artillery Quiver'
  | 'Ashen Wood Map'
  | 'Ashscale Talisman'
  | 'Assassin Bow'
  | "Assassin's Boots"
  | "Assassin's Garb"
  | "Assassin's Mitts"
  | 'Assembler Wand'
  | 'Astral Plate'
  | 'Astrolabe Amulet'
  | 'Atoll Map'
  | 'Atonement Mask'
  | 'Auric Mace'
  | 'Aventail Helmet'
  | 'Avian Twins Talisman'
  | 'Awl'
  | 'Azurite Flashpowder'
  | 'Banishing Blade'
  | 'Barbed Club'
  | 'Barbute Helmet'
  | 'Baroque Round Shield'
  | 'Barrows Map'
  | 'Basalt Flask'
  | 'Baselard'
  | 'Basemetal Treads'
  | 'Basic Disguise Kit'
  | 'Basilica Map'
  | 'Basket Rapier'
  | 'Bastard Sword'
  | 'Battered Foil'
  | 'Battered Helm'
  | 'Battery Staff'
  | 'Battle Buckler'
  | 'Battle Hammer'
  | 'Battle Lamellar'
  | 'Battle Plate'
  | 'Battle Sword'
  | 'Bazaar Map'
  | 'Beach Map'
  | 'Behemoth Mace'
  | 'Belfry Map'
  | 'Bismuth Flask'
  | 'Black Maw Talisman'
  | 'Bladed Mace'
  | 'Blasting Blade'
  | 'Blazing Arrow Quiver'
  | 'Blinder'
  | 'Blizzard Crown'
  | 'Blood Raiment'
  | 'Blood Sceptre'
  | 'Blue Pearl Amulet'
  | 'Blueprint: Bunker'
  | 'Blueprint: Laboratory'
  | 'Blueprint: Mansion'
  | 'Blueprint: Prohibited Library'
  | 'Blueprint: Records Office'
  | 'Blueprint: Repository'
  | "Blueprint: Smuggler's Den"
  | 'Blueprint: Tunnels'
  | 'Blueprint: Underbelly'
  | 'Blunt Arrow Quiver'
  | 'Blunt Arrow Quiver Piece'
  | 'Blunt Force Condenser'
  | 'Boarding Axe'
  | 'Bog Map'
  | 'Bone Armour'
  | 'Bone Bow'
  | 'Bone Circlet'
  | 'Bone Crypt Map'
  | 'Bone Helmet'
  | 'Bone Ring'
  | 'Bone Spirit Shield'
  | 'Bonespire Talisman'
  | 'Boom Mace'
  | 'Boot Blade'
  | 'Boot Knife'
  | 'Bramble Valley Map'
  | 'Branded Kite Shield'
  | 'Brass Maul'
  | 'Brass Spirit Shield'
  | 'Breach Ring'
  | 'Breakrib Talisman'
  | 'Brimstone Treads'
  | 'Broad Axe'
  | 'Broad Sword'
  | 'Broadhead Arrow Quiver'
  | 'Bronze Gauntlets'
  | 'Bronze Plate'
  | 'Bronze Sceptre'
  | 'Bronze Tower Shield'
  | 'Bronzescale Boots'
  | 'Bronzescale Gauntlets'
  | 'Buckskin Tower Shield'
  | 'Buckskin Tunic'
  | 'Burial Chambers Map'
  | 'Burnished Foil'
  | 'Burnished Spiked Shield'
  | 'Burst Band'
  | 'Butcher Axe'
  | 'Butcher Knife'
  | 'Butcher Sword'
  | 'Cabalist Regalia'
  | 'Cage Map'
  | 'Caldera Map'
  | 'Calling Wand'
  | 'Callous Mask'
  | 'Callous Mask Piece'
  | 'Candlestick Relic'
  | 'Canyon Map'
  | 'Capacity Rod'
  | 'Capricious Spiritblade'
  | 'Carcass Map'
  | 'Cardinal Round Shield'
  | 'Carnal Armour'
  | 'Carnal Boots'
  | 'Carnal Mitts'
  | 'Carnal Sceptre'
  | 'Carved Wand'
  | 'Carving Knife'
  | 'Castle Ruins Map'
  | "Cat's Paw"
  | 'Cedar Tower Shield'
  | 'Cells Map'
  | 'Cemetery Map'
  | 'Censer Relic'
  | 'Ceremonial Axe'
  | 'Ceremonial Kite Shield'
  | 'Ceremonial Mace'
  | 'Cerulean Ring'
  | 'Chain Belt'
  | 'Chain Boots'
  | 'Chain Gloves'
  | 'Chain Hauberk'
  | 'Chainmail Doublet'
  | 'Chainmail Tunic'
  | 'Chainmail Vest'
  | 'Champion Kite Shield'
  | 'Channel Map'
  | 'Chateau Map'
  | 'Chest Splitter'
  | 'Chestplate'
  | 'Chiming Spirit Shield'
  | 'Chrysalis Talisman'
  | 'Citadel Bow'
  | 'Citrine Amulet'
  | 'City Square Map'
  | 'Clasped Boots'
  | 'Clasped Mitts'
  | 'Cleaver'
  | 'Close Helmet'
  | 'Cloth Belt'
  | 'Cloth Belt Piece'
  | 'Cloudwhisper Boots'
  | 'Clutching Talisman'
  | 'Cobalt Jewel'
  | 'Coffer Relic'
  | 'Cogwork Ring'
  | 'Coiled Staff'
  | 'Coiled Wand'
  | 'Cold River Map'
  | 'Cold-attuned Buckler'
  | 'Colonnade Map'
  | 'Colossal Hybrid Flask'
  | 'Colossal Life Flask'
  | 'Colossal Mana Flask'
  | 'Colossal Tower Shield'
  | 'Colosseum Map'
  | 'Colosseum Plate'
  | 'Colossus Mallet'
  | "Commander's Brigandine"
  | 'Composite Bow'
  | 'Compound Bow'
  | 'Compound Spiked Shield'
  | 'Conduit Line'
  | 'Cone Helmet'
  | 'Congregator Wand'
  | 'Conjurer Boots'
  | 'Conjurer Gloves'
  | "Conjurer's Vestment"
  | 'Conquest Chainmail'
  | 'Conservatory Map'
  | 'Contract: Bunker'
  | 'Contract: Laboratory'
  | 'Contract: Mansion'
  | 'Contract: Prohibited Library'
  | 'Contract: Records Office'
  | 'Contract: Repository'
  | "Contract: Smuggler's Den"
  | 'Contract: Tunnels'
  | 'Contract: Underbelly'
  | 'Convening Wand'
  | 'Convoking Wand'
  | 'Copper Kris'
  | 'Copper Plate'
  | 'Copper Sword'
  | 'Copper Tower Shield'
  | 'Coral Amulet'
  | 'Coral Ring'
  | 'Coral Ruins Map'
  | 'Core Map'
  | 'Coronal Leather'
  | 'Coronal Maul'
  | 'Corroded Blade'
  | 'Corroded Tower Shield'
  | 'Corrugated Buckler'
  | 'Corsair Sword'
  | 'Corundum Flask'
  | 'Courtesan Sword'
  | 'Courthouse Map'
  | 'Courtyard Map'
  | 'Coves Map'
  | 'Crack Mace'
  | 'Crater Map'
  | 'Crescent Staff'
  | 'Crested Tower Shield'
  | 'Crimson Jewel'
  | 'Crimson Raiment'
  | 'Crimson Round Shield'
  | 'Crimson Temple Map'
  | 'Crimson Township Map'
  | 'Crude Bow'
  | 'Crude Sensing Charm'
  | 'Crude Ward'
  | 'Crusader Boots'
  | 'Crusader Buckler'
  | 'Crusader Chainmail'
  | 'Crusader Gloves'
  | 'Crusader Helmet'
  | 'Crusader Plate'
  | 'Crushing Force Magnifier'
  | 'Crypt Armour'
  | 'Crystal Belt'
  | 'Crystal Ore Map'
  | 'Crystal Sceptre'
  | 'Crystal Wand'
  | 'Cursed Crypt Map'
  | 'Curved Blade'
  | 'Cutlass'
  | "Cutthroat's Garb"
  | 'Dagger Axe'
  | 'Dark Forest Map'
  | 'Darksteel Treads'
  | 'Darkwood Sceptre'
  | 'Deadhand Talisman'
  | 'Death Bow'
  | 'Debilitation Gauntlets'
  | 'Decimation Bow'
  | 'Decorative Axe'
  | 'Decurve Bow'
  | 'Deep One Talisman'
  | 'Deerskin Boots'
  | 'Deerskin Gloves'
  | 'Defiled Cathedral Map'
  | 'Deicide Mask'
  | 'Demon Crown'
  | 'Demon Dagger'
  | "Demon's Horn"
  | 'Desert Brigandine'
  | 'Desert Map'
  | 'Desert Spring Map'
  | 'Despot Axe'
  | 'Destiny Leather'
  | 'Destroyer Regalia'
  | 'Devout Chainmail'
  | 'Diamond Flask'
  | 'Diamond Ring'
  | 'Dig Map'
  | 'Disapprobation Axe'
  | 'Divine Life Flask'
  | 'Divine Mana Flask'
  | 'Double Axe'
  | 'Double Claw'
  | 'Dragon Mace'
  | 'Dragonbone Rapier'
  | 'Dragonscale Boots'
  | 'Dragonscale Doublet'
  | 'Dragonscale Gauntlets'
  | 'Dragoon Sword'
  | 'Dread Maul'
  | 'Dream Mace'
  | 'Dreamquest Slippers'
  | 'Driftwood Club'
  | 'Driftwood Maul'
  | 'Driftwood Sceptre'
  | 'Driftwood Spiked Shield'
  | 'Driftwood Wand'
  | 'Dry Sea Map'
  | 'Dunes Map'
  | 'Dungeon Map'
  | 'Dusk Blade'
  | 'Dusk Ring'
  | 'Duskwalk Slippers'
  | 'Eagle Claw'
  | 'Ebony Tower Shield'
  | 'Eclipse Staff'
  | 'Eelskin Boots'
  | 'Eelskin Gloves'
  | 'Eelskin Sole'
  | 'Eelskin Tunic'
  | "Einhar's Memory"
  | 'Elder Sword'
  | 'Elegant Foil'
  | 'Elegant Ringmail'
  | 'Elegant Round Shield'
  | 'Elegant Sword'
  | 'Embroidered Gloves'
  | 'Enamel Brooch'
  | 'Enameled Buckler'
  | 'Endothermic Buckler'
  | 'Engraved Greatsword'
  | 'Engraved Hatchet'
  | 'Engraved Wand'
  | 'Espionage Disguise Kit'
  | 'Essential Keyring'
  | 'Estoc'
  | 'Estuary Map'
  | 'Etched Greatsword'
  | 'Etched Hatchet'
  | 'Etched Kite Shield'
  | 'Eternal Burgonet'
  | 'Eternal Life Flask'
  | 'Eternal Mana Flask'
  | 'Eternal Sword'
  | 'Eventuality Rod'
  | 'Excavation Map'
  | 'Exhausting Spirit Shield'
  | 'Exothermic Tower Shield'
  | 'Expedition Logbook'
  | 'Exquisite Blade'
  | 'Exquisite Leather'
  | 'Eye Gouger'
  | 'Ezomyte Axe'
  | 'Ezomyte Blade'
  | 'Ezomyte Burgonet'
  | 'Ezomyte Dagger'
  | 'Ezomyte Spiked Shield'
  | 'Ezomyte Staff'
  | 'Ezomyte Tower Shield'
  | 'Factory Map'
  | 'Familial Contract'
  | 'Fancy Foil'
  | 'Fangjaw Talisman'
  | "Faun's Horn"
  | 'Feathered Arrow Quiver'
  | 'Fencer Helm'
  | 'Festival Mask'
  | 'Fickle Spiritblade'
  | 'Field Lamellar'
  | 'Fields Map'
  | 'Fiend Dagger'
  | 'Fine Lockpick'
  | 'Fine Sensing Charm'
  | 'Fine Sharpening Stone'
  | 'Fingerless Silk Gloves'
  | 'Fir Round Shield'
  | 'Fire Arrow Quiver'
  | 'Fishing Rod'
  | 'Fishscale Gauntlets'
  | 'Flanged Arrowhead'
  | 'Flanged Drill'
  | 'Flanged Mace'
  | 'Flare Mace'
  | 'Flashfire Blade'
  | 'Flaying Knife'
  | 'Fleshripper'
  | 'Flickerflame Blade'
  | 'Flooded Mine Map'
  | 'Fluted Bascinet'
  | 'Focal Stone'
  | 'Foliate Brooch'
  | 'Footman Sword'
  | 'Forbidden Woods Map'
  | 'Forge of the Phoenix Map'
  | 'Forking River Map'
  | 'Fossilised Spirit Shield'
  | 'Foul Staff'
  | 'Foundry Bow'
  | 'Foundry Map'
  | 'Foxhide Sole'
  | 'Fragmenting Arrowhead'
  | 'Fright Claw'
  | 'Fright Maul'
  | 'Frontier Leather'
  | 'Frozen Cabins Map'
  | 'Fugitive Boots'
  | 'Full Chainmail'
  | 'Full Dragonscale'
  | 'Full Leather'
  | 'Full Plate'
  | 'Full Ringmail'
  | 'Full Scale Armour'
  | 'Full Wyrmscale'
  | 'Fungal Hollow Map'
  | 'Gale Crown'
  | 'Gardens Map'
  | 'Gauche Gloves'
  | 'Gavel'
  | 'Gemini Claw'
  | 'Gemstone Sword'
  | "General's Brigandine"
  | 'Geode Map'
  | 'Geodesic Ring'
  | 'Ghastly Eye Jewel'
  | 'Ghetto Map'
  | 'Giant Life Flask'
  | 'Giant Mana Flask'
  | 'Gilded Axe'
  | 'Gilded Buckler'
  | 'Gilded Sallet'
  | 'Girded Tower Shield'
  | 'Glacier Map'
  | 'Gladiator Helmet'
  | 'Gladiator Plate'
  | 'Gladius'
  | 'Glass Shank'
  | 'Gloam Ring'
  | 'Glorious Leather'
  | 'Glorious Plate'
  | 'Gnarled Branch'
  | 'Goathide Boots'
  | 'Goathide Buckler'
  | 'Goathide Gloves'
  | 'Gold Amulet'
  | 'Gold Flask'
  | 'Gold Ring'
  | 'Golden Brooch'
  | 'Golden Buckler'
  | 'Golden Kris'
  | 'Golden Mask'
  | 'Golden Plate'
  | 'Goliath Gauntlets'
  | 'Goliath Greaves'
  | 'Gouger'
  | 'Graceful Sword'
  | 'Grand Life Flask'
  | 'Grand Mana Flask'
  | 'Grandmaster Keyring'
  | 'Granite Flask'
  | 'Grappler'
  | 'Grasping Mail'
  | 'Grave Trough Map'
  | 'Graveyard Map'
  | 'Great Crown'
  | 'Great Helmet'
  | 'Great Mallet'
  | 'Great White Claw'
  | 'Greater Life Flask'
  | 'Greater Mana Flask'
  | 'Greatwolf Talisman'
  | 'Grinning Fetish'
  | 'Gripped Gloves'
  | 'Grotto Map'
  | 'Grove Bow'
  | 'Gruelling Gauntlets'
  | 'Gut Ripper'
  | 'Gutting Knife'
  | 'Hallowed Hybrid Flask'
  | 'Hallowed Life Flask'
  | 'Hallowed Mana Flask'
  | 'Hammered Buckler'
  | 'Harbinger Bow'
  | 'Harbinger Map'
  | 'Harlequin Mask'
  | 'Harmonic Spirit Shield'
  | 'Harpy Rapier'
  | 'Haunted Mansion Map'
  | "Headman's Sword"
  | 'Headsman Axe'
  | 'Heat-attuned Tower Shield'
  | 'Heathen Wand'
  | 'Heavy Arrow Quiver'
  | 'Heavy Belt'
  | 'Hedron Bow'
  | "Hellion's Paw"
  | 'Hexclaw Talisman'
  | 'Highborn Bow'
  | 'Highborn Staff'
  | 'Highland Blade'
  | 'Hollowpoint Arrowhead'
  | 'Hollowpoint Dagger'
  | 'Holy Chainmail'
  | 'Honed Cleaver'
  | 'Hooded Cloak'
  | 'Hook Sword'
  | 'Horned Sceptre'
  | 'Horned Talisman'
  | 'Hubris Circlet'
  | 'Hunter Hood'
  | 'Hussar Brigandine'
  | 'Hydrascale Boots'
  | 'Hydrascale Gauntlets'
  | 'Hypnotic Eye Jewel'
  | 'Iceberg Map'
  | 'Imbued Wand'
  | 'Imp Crown'
  | 'Imp Dagger'
  | 'Impact Force Propagator'
  | 'Imperial Bow'
  | 'Imperial Buckler'
  | 'Imperial Claw'
  | 'Imperial Maul'
  | 'Imperial Skean'
  | 'Imperial Staff'
  | 'Imperial Staff Piece'
  | 'Incandescent Invitation'
  | 'Infantry Brigandine'
  | 'Infernal Axe'
  | 'Infernal Blade'
  | 'Infernal Sword'
  | 'Infested Valley Map'
  | 'Iolite Ring'
  | 'Iron Circlet'
  | 'Iron Flask'
  | 'Iron Gauntlets'
  | 'Iron Greaves'
  | 'Iron Hat'
  | 'Iron Mask'
  | 'Iron Ring'
  | 'Iron Sceptre'
  | 'Iron Staff'
  | 'Ironscale Boots'
  | 'Ironscale Gauntlets'
  | 'Ironwood Buckler'
  | 'Ivory Bow'
  | 'Ivory Spirit Shield'
  | 'Ivory Temple Map'
  | 'Jade Amulet'
  | 'Jade Chopper'
  | 'Jade Flask'
  | 'Jade Hatchet'
  | 'Jagged Foil'
  | 'Jagged Maul'
  | 'Jasper Axe'
  | 'Jasper Chopper'
  | 'Jewelled Foil'
  | 'Jingling Spirit Shield'
  | 'Judgement Staff'
  | 'Jungle Valley Map'
  | 'Karui Axe'
  | 'Karui Chopper'
  | 'Karui Maul'
  | 'Karui Sceptre'
  | "Kirac's Memory"
  | 'Laboratory Map'
  | 'Labrys'
  | 'Lacewood Spirit Shield'
  | 'Lacquered Buckler'
  | 'Lacquered Garb'
  | 'Lacquered Helmet'
  | 'Lair Map'
  | 'Lair of the Hydra Map'
  | 'Laminated Kite Shield'
  | 'Lapis Amulet'
  | 'Large Cluster Jewel'
  | 'Large Hybrid Flask'
  | 'Large Life Flask'
  | 'Large Mana Flask'
  | 'Lathi'
  | 'Latticed Ringmail'
  | 'Lava Chamber Map'
  | 'Lava Lake Map'
  | 'Layered Kite Shield'
  | 'Lead Sceptre'
  | 'Leather Belt'
  | 'Leather Bracers'
  | 'Leather Cap'
  | 'Leather Hood'
  | 'Leatherscale Boots'
  | 'Legion Boots'
  | 'Legion Gloves'
  | 'Legion Hammer'
  | 'Legion Sword'
  | 'Legion Sword Piece'
  | 'Leyline Gloves'
  | 'Leyline Map'
  | 'Light Brigandine'
  | 'Lighthouse Map'
  | 'Linden Kite Shield'
  | 'Lion Pelt'
  | 'Lion Sword'
  | 'Lithe Blade'
  | 'Lone Antler Talisman'
  | 'Long Bow'
  | 'Long Staff'
  | 'Longsword'
  | 'Longtooth Talisman'
  | 'Lookout Map'
  | 'Lordly Plate'
  | 'Loricated Ringmail'
  | 'Lunaris Circlet'
  | 'Lustrous Ward'
  | 'Maelström Staff'
  | "Mage's Vestment"
  | 'Magistrate Crown'
  | 'Magmatic Tower Shield'
  | 'Mahogany Tower Shield'
  | 'Majestic Plate'
  | 'Malformation Map'
  | 'Malign Fangs'
  | 'Mallet'
  | 'Maltreatment Axe'
  | 'Mandible Talisman'
  | 'Maple Round Shield'
  | 'Maraketh Bow'
  | 'Marble Amulet'
  | 'Marshes Map'
  | 'Master Lockpick'
  | 'Mausoleum Map'
  | "Maven's Invitation: The Atlas"
  | "Maven's Invitation: The Elderslayers"
  | "Maven's Invitation: The Feared"
  | "Maven's Invitation: The Forgotten"
  | "Maven's Invitation: The Formed"
  | "Maven's Invitation: The Hidden"
  | "Maven's Invitation: The Twisted"
  | 'Maze Map'
  | 'Maze of the Minotaur Map'
  | 'Meatgrinder'
  | 'Mechalarm Belt'
  | 'Medium Cluster Jewel'
  | 'Medium Hybrid Flask'
  | 'Medium Life Flask'
  | 'Medium Mana Flask'
  | 'Mesa Map'
  | 'Mesh Boots'
  | 'Mesh Gloves'
  | 'Micro-Distillery Belt'
  | 'Midnight Blade'
  | 'Military Staff'
  | 'Mind Cage'
  | 'Mineral Pools Map'
  | 'Mirrored Spiked Shield'
  | 'Monkey Paw Talisman'
  | 'Monkey Twins Talisman'
  | 'Moon Staff'
  | 'Moon Temple Map'
  | 'Moonstone Ring'
  | 'Morning Star'
  | 'Mosaic Kite Shield'
  | 'Mud Geyser Map'
  | 'Murder Boots'
  | 'Murder Mitts'
  | 'Murderous Eye Jewel'
  | 'Museum Map'
  | 'Nailed Fist'
  | 'Naval Contract'
  | 'Necromancer Circlet'
  | 'Necromancer Silks'
  | 'Necropolis Map'
  | 'Nexus Gloves'
  | 'Nightmare Bascinet'
  | 'Nightmare Mace'
  | 'Nightwind Slippers'
  | "Niko's Memory"
  | 'Noble Axe'
  | 'Noble Claw'
  | 'Noble Tricorne'
  | 'Nubuck Boots'
  | 'Nubuck Gloves'
  | 'Oak Buckler'
  | 'Obsidian Sharpening Stone'
  | "Occultist's Vestment"
  | 'Ochre Sceptre'
  | 'Oiled Coat'
  | 'Oiled Vest'
  | 'Omen Wand'
  | 'Onyx Amulet'
  | 'Opal Ring'
  | 'Opal Sceptre'
  | 'Opal Wand'
  | 'Orchard Map'
  | 'Ornate Mace'
  | 'Ornate Quiver'
  | 'Ornate Ringmail'
  | 'Ornate Spiked Shield'
  | 'Ornate Sword'
  | 'Oscillating Sceptre'
  | 'Overgrown Ruin Map'
  | 'Overgrown Shrine Map'
  | 'Padded Jacket'
  | 'Padded Vest'
  | 'Pagan Wand'
  | 'Painted Buckler'
  | 'Painted Tower Shield'
  | 'Palace Map'
  | 'Papyrus Relic'
  | 'Park Map'
  | 'Paua Amulet'
  | 'Paua Ring'
  | 'Pecoraro'
  | 'Pen Map'
  | 'Penetrating Arrow Quiver'
  | 'Peninsula Map'
  | 'Penitent Mask'
  | 'Penumbra Ring'
  | 'Pernach'
  | 'Petrified Club'
  | 'Phantasmagoria Map'
  | 'Phantom Mace'
  | 'Pier Map'
  | 'Pig-Faced Bascinet'
  | 'Piledriver'
  | 'Pine Buckler'
  | 'Pinnacle Tower Shield'
  | 'Pit Map'
  | 'Pit of the Chimera Map'
  | 'Plague Mask'
  | 'Plank Kite Shield'
  | 'Plate Vest'
  | 'Plateau Map'
  | 'Plated Gauntlets'
  | 'Plated Greaves'
  | 'Plated Maul'
  | 'Platinum Kris'
  | 'Platinum Sceptre'
  | 'Plaza Map'
  | 'Pneumatic Dagger'
  | 'Poignard'
  | 'Polar Buckler'
  | 'Polaric Invitation'
  | 'Poleaxe'
  | 'Polished Sensing Charm'
  | 'Polished Spiked Shield'
  | 'Port Map'
  | 'Potentiality Rod'
  | 'Praetor Crown'
  | 'Precinct Map'
  | 'Precise Arrowhead'
  | 'Prehistoric Claw'
  | 'Pressurised Dagger'
  | 'Preventative Contract'
  | 'Primal Arrow Quiver'
  | 'Primal Skull Talisman'
  | 'Prime Cleaver'
  | 'Primeval Rapier'
  | 'Primitive Staff'
  | 'Primordial Blocks Map'
  | 'Primordial Pool Map'
  | 'Primordial Staff'
  | 'Prismatic Jewel'
  | 'Prismatic Ring'
  | 'Processional Relic'
  | 'Profane Wand'
  | 'Promenade Map'
  | 'Prong Dagger'
  | 'Prophecy Wand'
  | 'Prophet Crown'
  | 'Psychotic Axe'
  | 'Quarterstaff'
  | 'Quartz Flask'
  | 'Quartz Sceptre'
  | 'Quartz Wand'
  | 'Quicksilver Flask'
  | 'Quilted Jacket'
  | 'Racecourse Map'
  | 'Ramparts Map'
  | 'Ranger Bow'
  | 'Raven Mask'
  | 'Rawhide Boots'
  | 'Rawhide Gloves'
  | 'Rawhide Tower Shield'
  | 'Reaver Axe'
  | 'Reaver Helmet'
  | 'Reaver Sword'
  | 'Rebuking Blade'
  | 'Reciprocation Staff'
  | 'Recurve Bow'
  | 'Redwood Spiked Shield'
  | 'Reef Map'
  | 'Reflex Bow'
  | 'Regicide Disguise Kit'
  | 'Regicide Mask'
  | 'Reinforced Greaves'
  | 'Reinforced Kite Shield'
  | 'Reinforced Tower Shield'
  | 'Relic Chambers Map'
  | 'Residence Map'
  | 'Ring'
  | 'Ringmail Boots'
  | 'Ringmail Coat'
  | 'Ringmail Gloves'
  | 'Ritual Sceptre'
  | 'Riveted Boots'
  | 'Riveted Gloves'
  | 'Rock Breaker'
  | 'Rot Head Talisman'
  | 'Rotfeather Talisman'
  | 'Rotted Round Shield'
  | 'Rough Sharpening Stone'
  | 'Royal Axe'
  | 'Royal Bow'
  | 'Royal Burgonet'
  | 'Royal Sceptre'
  | 'Royal Skean'
  | 'Royal Staff'
  | 'Ruby Flask'
  | 'Ruby Ring'
  | 'Runed Bracers'
  | 'Runic Crest'
  | 'Runic Crown'
  | 'Runic Gages'
  | 'Runic Gauntlets'
  | 'Runic Gloves'
  | 'Runic Greaves'
  | 'Runic Hatchet'
  | 'Runic Helm'
  | 'Runic Sabatons'
  | 'Runic Sollerets'
  | 'Rusted Coif'
  | 'Rusted Hatchet'
  | 'Rusted Spike'
  | 'Rusted Sword'
  | 'Rustic Sash'
  | 'Sabre'
  | 'Sacred Hybrid Flask'
  | 'Sacred Life Flask'
  | 'Sacred Mana Flask'
  | 'Sacrificial Garb'
  | 'Sadist Garb'
  | 'Sage Wand'
  | "Sage's Robe"
  | 'Sai'
  | "Saint's Hauberk"
  | 'Saintly Chainmail'
  | 'Sallet'
  | 'Sambar Sceptre'
  | 'Samite Gloves'
  | 'Samite Slippers'
  | 'Samnite Helmet'
  | 'Sanctified Life Flask'
  | 'Sanctified Mana Flask'
  | 'Sapphire Flask'
  | 'Sapphire Ring'
  | 'Satin Gloves'
  | 'Satin Slippers'
  | "Savant's Robe"
  | 'Scale Doublet'
  | 'Scale Vest'
  | 'Scare Mask'
  | 'Scarlet Raiment'
  | 'Scarlet Round Shield'
  | 'Scholar Boots'
  | "Scholar's Robe"
  | 'Screaming Invitation'
  | 'Scriptorium Map'
  | 'Seaglass Amulet'
  | 'Searching Eye Jewel'
  | 'Secutor Helm'
  | 'Sekhem'
  | 'Sentinel Jacket'
  | 'Sepulchre Map'
  | 'Serpentine Staff'
  | 'Serpentscale Boots'
  | 'Serpentscale Gauntlets'
  | 'Serrated Arrow Quiver'
  | 'Serrated Foil'
  | 'Shabby Jerkin'
  | 'Shackled Boots'
  | 'Shadow Axe'
  | 'Shadow Fangs'
  | 'Shadow Sceptre'
  | 'Shadowed Ring'
  | 'Shagreen Boots'
  | 'Shagreen Gloves'
  | 'Shagreen Tower Shield'
  | 'Sharkskin Boots'
  | 'Sharkskin Gloves'
  | 'Sharkskin Tunic'
  | 'Sharktooth Arrow Quiver'
  | 'Sharktooth Claw'
  | 'Shining Ward'
  | 'Shipyard Map'
  | 'Shore Map'
  | 'Short Bow'
  | 'Shrine Map'
  | 'Siege Axe'
  | 'Siege Helmet'
  | 'Siege Map'
  | 'Silk Gloves'
  | 'Silk Robe'
  | 'Silk Slippers'
  | 'Silken Garb'
  | 'Silken Hood'
  | 'Silken Vest'
  | 'Silken Wrap'
  | 'Silkweave Sole'
  | 'Silo Map'
  | 'Silver Brooch'
  | 'Silver Flask'
  | 'Simple Lockpick'
  | 'Simple Robe'
  | 'Simplex Amulet'
  | 'Sinistral Gloves'
  | 'Sinner Tricorne'
  | 'Skean'
  | 'Skeleton Keyring'
  | 'Skinning Knife'
  | 'Slaughter Knife'
  | 'Sledgehammer'
  | 'Sleek Coat'
  | 'Slink Boots'
  | 'Slink Gloves'
  | 'Small Cluster Jewel'
  | 'Small Hybrid Flask'
  | 'Small Life Flask'
  | 'Small Mana Flask'
  | 'Smallsword'
  | 'Sniper Bow'
  | 'Solar Maul'
  | 'Solarine Bow'
  | 'Solaris Circlet'
  | 'Soldier Boots'
  | 'Soldier Gloves'
  | 'Soldier Helmet'
  | "Soldier's Brigandine"
  | 'Sorcerer Boots'
  | 'Sorcerer Gloves'
  | 'Sorrow Mask'
  | 'Southswing Gloves'
  | 'Sovereign Spiked Shield'
  | 'Sparkling Claw'
  | 'Spectral Axe'
  | 'Spectral Sword'
  | 'Spider Forest Map'
  | 'Spider Lair Map'
  | 'Spidersilk Robe'
  | 'Spike-Point Arrow Quiver'
  | 'Spiked Bundle'
  | 'Spiked Club'
  | 'Spiked Gloves'
  | 'Spiked Round Shield'
  | 'Spine Bow'
  | 'Spinefuse Talisman'
  | 'Spiny Maul'
  | 'Spiny Round Shield'
  | 'Spiraled Foil'
  | 'Spiraled Wand'
  | 'Splendid Round Shield'
  | 'Splintered Tower Shield'
  | 'Splitnewt Talisman'
  | 'Stabilising Sceptre'
  | 'Stag Sceptre'
  | 'Stagnation Map'
  | 'Standard Lockpick'
  | 'Standard Sharpening Stone'
  | 'Stealth Boots'
  | 'Stealth Gloves'
  | 'Steel Bracers'
  | 'Steel Circlet'
  | 'Steel Drill'
  | 'Steel Gauntlets'
  | 'Steel Greaves'
  | 'Steel Kite Shield'
  | 'Steel Ring'
  | 'Steelhead'
  | 'Steelscale Boots'
  | 'Steelscale Gauntlets'
  | 'Steelwood Bow'
  | 'Stibnite Flask'
  | 'Stiletto'
  | 'Stone Axe'
  | 'Stone Hammer'
  | 'Stormrider Boots'
  | 'Strand Map'
  | 'Strapped Boots'
  | 'Strapped Leather'
  | 'Strapped Mitts'
  | 'Studded Belt'
  | 'Studded Bracers'
  | 'Studded Round Shield'
  | 'Stygian Vise'
  | 'Subsuming Spirit Shield'
  | 'Sulphur Blowtorch'
  | 'Sulphur Flask'
  | 'Sulphur Vents Map'
  | 'Summit Map'
  | 'Sun Leather'
  | 'Sun Plate'
  | 'Sundering Axe'
  | 'Sunken City Map'
  | 'Supreme Spiked Shield'
  | 'Synthesised Map'
  | 'Talon Axe'
  | 'Tarnished Spirit Shield'
  | 'Tattered Cloak'
  | 'Taxing Gauntlets'
  | 'Teak Round Shield'
  | 'Tempered Foil'
  | 'Temple Map'
  | 'Tenderizer'
  | 'Tenebrous Ring'
  | 'Terrace Map'
  | 'Terror Claw'
  | 'Terror Maul'
  | 'Thaumaturgical Sensing Charm'
  | 'Thaumaturgical Ward'
  | 'Thaumetic Blowtorch'
  | 'Thaumetic Flashpowder'
  | 'Theatre Disguise Kit'
  | 'Thicket Bow'
  | 'Thicket Map'
  | "Thief's Garb"
  | "Thief's Trinket"
  | 'Thorium Spirit Shield'
  | 'Thorn Rapier'
  | 'Three Hands Talisman'
  | 'Three Rat Talisman'
  | 'Thresher Claw'
  | 'Throat Stabber'
  | 'Tiger Hook'
  | 'Tiger Sword'
  | "Tiger's Paw"
  | 'Timber Axe'
  | 'Timeless Jewel'
  | 'Timeworn Claw'
  | 'Titan Gauntlets'
  | 'Titan Greaves'
  | 'Titanium Spirit Shield'
  | 'Tomahawk'
  | 'Tome Relic'
  | 'Topaz Flask'
  | 'Topaz Ring'
  | 'Torn Cloak'
  | 'Tornado Wand'
  | 'Torture Cage'
  | 'Totemic Maul'
  | 'Tower Map'
  | 'Toxic Sewer Map'
  | 'Transfer-attuned Spirit Shield'
  | 'Transformer Staff'
  | 'Trapper Boots'
  | 'Trapper Mitts'
  | 'Trarthan Flashpowder'
  | 'Tribal Circlet'
  | 'Tribal Club'
  | 'Tribal Maul'
  | 'Tricorne'
  | 'Trisula'
  | 'Triumphant Lamellar'
  | 'Tropical Island Map'
  | 'Turquoise Amulet'
  | 'Twig Spirit Shield'
  | 'Twilight Blade'
  | 'Twin Claw'
  | 'Two-Handed Sword'
  | 'Two-Point Arrow Quiver'
  | 'Two-Stone Ring'
  | 'Two-Toned Boots'
  | "Tyrant's Sekhem"
  | 'Ultimatum Aspect'
  | 'Underground River Map'
  | 'Underground Sea Map'
  | 'Undying Flesh Talisman'
  | 'Unset Amulet'
  | 'Unset Ring'
  | 'Urn Relic'
  | 'Ursine Pelt'
  | 'Vaal Axe'
  | 'Vaal Blade'
  | 'Vaal Buckler'
  | 'Vaal Claw'
  | 'Vaal Gauntlets'
  | 'Vaal Greatsword'
  | 'Vaal Greaves'
  | 'Vaal Hatchet'
  | 'Vaal Mask'
  | 'Vaal Pyramid Map'
  | 'Vaal Rapier'
  | 'Vaal Regalia'
  | 'Vaal Sceptre'
  | 'Vaal Spirit Shield'
  | 'Vaal Temple Map'
  | 'Vanguard Belt'
  | 'Variscite Blade'
  | 'Varnished Coat'
  | 'Vault Map'
  | 'Velvet Gloves'
  | 'Velvet Slippers'
  | 'Vengeful Contract'
  | 'Vermillion Ring'
  | 'Versatile Keyring'
  | 'Vigilante Contract'
  | 'Vile Arrow Quiver'
  | 'Vile Staff'
  | 'Villa Map'
  | 'Vine Circlet'
  | 'Viridian Jewel'
  | 'Visored Sallet'
  | 'Void Axe'
  | 'Void Fangs'
  | 'Void Sceptre'
  | 'Volcano Map'
  | 'Voltaxic Flashpowder'
  | 'Walnut Spirit Shield'
  | 'War Axe'
  | 'War Buckler'
  | 'War Hammer'
  | 'War Plate'
  | 'War Sword'
  | 'Waste Pool Map'
  | 'Wasteland Map'
  | 'Waterways Map'
  | 'Waxed Garb'
  | 'Wereclaw Talisman'
  | 'Whalebone Rapier'
  | 'Wharf Map'
  | 'Whisper-woven Cloak'
  | 'Widowsilk Robe'
  | 'Wild Leather'
  | 'Windbreak Boots'
  | 'Winged Sole'
  | 'Winter Crown'
  | 'Wolf Pelt'
  | 'Woodful Staff'
  | 'Woodsplitter'
  | 'Wool Gloves'
  | 'Wool Shoes'
  | 'Wraith Axe'
  | 'Wraith Sword'
  | 'Wrapped Boots'
  | 'Wrapped Mitts'
  | 'Wrist Chopper'
  | 'Writhing Invitation'
  | 'Writhing Talisman'
  | 'Wyrm Mace'
  | 'Wyrmbone Rapier'
  | 'Wyrmscale Boots'
  | 'Wyrmscale Doublet'
  | 'Wyrmscale Gauntlets'
  | 'Yew Spirit Shield'
  | 'Zealot Boots'
  | 'Zealot Gloves'
  | 'Zealot Helmet'
  | 'Zodiac Leather'
