export type ItemBaseType =
  | 'Abyssal Axe'
  | 'Abyssal Sceptre'
  | 'Academy Map'
  | 'Accumulator Wand'
  | 'Acid Caverns Map'
  | 'Aetherwind Gloves'
  | 'Agate Amulet'
  | 'Aggregator Charm'
  | 'Alder Spiked Shield'
  | 'Alleyways Map'
  | 'Alloyed Spiked Shield'
  | 'Alternating Sceptre'
  | "Alva's Memory"
  | 'Amber Amulet'
  | 'Ambush Boots'
  | 'Ambush Mitts'
  | 'Ambusher'
  | 'Amethyst Flask'
  | 'Amethyst Ring'
  | 'Anarchic Spiritblade'
  | 'Ancestral Club'
  | 'Ancient City Map'
  | 'Ancient Gauntlets'
  | 'Ancient Greaves'
  | 'Ancient Spirit Shield'
  | 'Ancient Sword'
  | 'Angelic Kite Shield'
  | 'Antique Gauntlets'
  | 'Antique Greaves'
  | 'Antique Rapier'
  | 'Apex Cleaver'
  | 'Apex Rapier'
  | "Apothecary's Gloves"
  | 'Aquamarine Flask'
  | 'Arachnid Nest Map'
  | 'Arachnid Tomb Map'
  | 'Arcade Map'
  | 'Arcanist Gloves'
  | 'Arcanist Slippers'
  | 'Archdemon Crown'
  | 'Archon Kite Shield'
  | 'Archon Kite Shield Piece'
  | 'Arena Map'
  | 'Arena Plate'
  | 'Arid Lake Map'
  | 'Arming Axe'
  | 'Armoury Map'
  | 'Arsenal Map'
  | 'Artillery Quiver'
  | 'Ashen Wood Map'
  | 'Ashscale Talisman'
  | 'Assassin Bow'
  | "Assassin's Boots"
  | "Assassin's Garb"
  | "Assassin's Mitts"
  | 'Assembler Wand'
  | 'Astral Plate'
  | 'Astrolabe Amulet'
  | 'Atoll Map'
  | 'Atonement Mask'
  | 'Auric Mace'
  | 'Aventail Helmet'
  | 'Avian Twins Talisman'
  | 'Awl'
  | 'Azurite Flashpowder'
  | 'Banishing Blade'
  | 'Barbed Club'
  | 'Barbute Helmet'
  | 'Baroque Round Shield'
  | 'Barrows Map'
  | 'Basalt Flask'
  | 'Baselard'
  | 'Basemetal Treads'
  | 'Basic Disguise Kit'
  | 'Basilica Map'
  | 'Basket Rapier'
  | 'Bastard Sword'
  | 'Battered Foil'
  | 'Battered Helm'
  | 'Battery Staff'
  | 'Battle Buckler'
  | 'Battle Hammer'
  | 'Battle Lamellar'
  | 'Battle Plate'
  | 'Battle Sword'
  | 'Bazaar Map'
  | 'Beach Map'
  | 'Behemoth Mace'
  | 'Belfry Map'
  | 'Bismuth Flask'
  | 'Black Maw Talisman'
  | 'Bladed Mace'
  | 'Blasting Blade'
  | 'Blazing Arrow Quiver'
  | 'Blinder'
  | 'Blizzard Crown'
  | 'Blood Raiment'
  | 'Blood Sceptre'
  | 'Blue Pearl Amulet'
  | 'Blueprint: Bunker'
  | 'Blueprint: Laboratory'
  | 'Blueprint: Mansion'
  | 'Blueprint: Prohibited Library'
  | 'Blueprint: Records Office'
  | 'Blueprint: Repository'
  | "Blueprint: Smuggler's Den"
  | 'Blueprint: Tunnels'
  | 'Blueprint: Underbelly'
  | 'Blunt Arrow Quiver'
  | 'Blunt Arrow Quiver Piece'
  | 'Blunt Force Condenser'
  | 'Boarding Axe'
  | 'Bog Map'
  | 'Bone Armour'
  | 'Bone Bow'
  | 'Bone Circlet'
  | 'Bone Crypt Map'
  | 'Bone Helmet'
  | 'Bone Ring'
  | 'Bone Spirit Shield'
  | 'Bonespire Talisman'
  | 'Boom Mace'
  | 'Boot Blade'
  | 'Boot Knife'
  | 'Bramble Valley Map'
  | 'Branded Kite Shield'
  | 'Brass Maul'
  | 'Brass Spirit Shield'
  | 'Breach Ring'
  | 'Breakrib Talisman'
  | 'Brimstone Treads'
  | 'Broad Axe'
  | 'Broad Sword'
  | 'Broadhead Arrow Quiver'
  | 'Bronze Gauntlets'
  | 'Bronze Plate'
  | 'Bronze Sceptre'
  | 'Bronze Tower Shield'
  | 'Bronzescale Boots'
  | 'Bronzescale Gauntlets'
  | 'Buckskin Tower Shield'
  | 'Buckskin Tunic'
  | 'Burial Chambers Map'
  | 'Burnished Foil'
  | 'Burnished Spiked Shield'
  | 'Burst Band'
  | 'Butcher Axe'
  | 'Butcher Knife'
  | 'Butcher Sword'
  | 'Cabalist Regalia'
  | 'Cage Map'
  | 'Caldera Map'
  | 'Calling Wand'
  | 'Callous Mask'
  | 'Callous Mask Piece'
  | 'Candlestick Relic'
  | 'Canyon Map'
  | 'Capacity Rod'
  | 'Capricious Spiritblade'
  | 'Carcass Map'
  | 'Cardinal Round Shield'
  | 'Carnal Armour'
  | 'Carnal Boots'
  | 'Carnal Mitts'
  | 'Carnal Sceptre'
  | 'Carved Wand'
  | 'Carving Knife'
  | 'Castle Ruins Map'
  | "Cat's Paw"
  | 'Cedar Tower Shield'
  | 'Cells Map'
  | 'Cemetery Map'
  | 'Censer Relic'
  | 'Ceremonial Axe'
  | 'Ceremonial Kite Shield'
  | 'Ceremonial Mace'
  | 'Cerulean Ring'
  | 'Chain Belt'
  | 'Chain Boots'
  | 'Chain Gloves'
  | 'Chain Hauberk'
  | 'Chainmail Doublet'
  | 'Chainmail Tunic'
  | 'Chainmail Vest'
  | 'Champion Kite Shield'
  | 'Channel Map'
  | 'Chateau Map'
  | 'Chest Splitter'
  | 'Chestplate'
  | 'Chiming Spirit Shield'
  | 'Chrysalis Talisman'
  | 'Citadel Bow'
  | 'Citrine Amulet'
  | 'City Square Map'
  | 'Clasped Boots'
  | 'Clasped Mitts'
  | 'Cleaver'
  | 'Close Helmet'
  | 'Cloth Belt'
  | 'Cloth Belt Piece'
  | 'Cloudwhisper Boots'
  | 'Clutching Talisman'
  | 'Cobalt Jewel'
  | 'Coffer Relic'
  | 'Cogwork Ring'
  | 'Coiled Staff'
  | 'Coiled Wand'
  | 'Cold River Map'
  | 'Cold-attuned Buckler'
  | 'Colonnade Map'
  | 'Colossal Hybrid Flask'
  | 'Colossal Life Flask'
  | 'Colossal Mana Flask'
  | 'Colossal Tower Shield'
  | 'Colosseum Map'
  | 'Colosseum Plate'
  | 'Colossus Mallet'
  | "Commander's Brigandine"
  | 'Composite Bow'
  | 'Compound Bow'
  | 'Compound Spiked Shield'
  | 'Conduit Line'
  | 'Cone Helmet'
  | 'Congregator Wand'
  | 'Conjurer Boots'
  | 'Conjurer Gloves'
  | "Conjurer's Vestment"
  | 'Conquest Chainmail'
  | 'Conservatory Map'
  | 'Contract: Bunker'
  | 'Contract: Laboratory'
  | 'Contract: Mansion'
  | 'Contract: Prohibited Library'
  | 'Contract: Records Office'
  | 'Contract: Repository'
  | "Contract: Smuggler's Den"
  | 'Contract: Tunnels'
  | 'Contract: Underbelly'
  | 'Convening Wand'
  | 'Convoking Wand'
  | 'Copper Kris'
  | 'Copper Plate'
  | 'Copper Sword'
  | 'Copper Tower Shield'
  | 'Coral Amulet'
  | 'Coral Ring'
  | 'Coral Ruins Map'
  | 'Core Map'
  | 'Coronal Leather'
  | 'Coronal Maul'
  | 'Corroded Blade'
  | 'Corroded Tower Shield'
  | 'Corrugated Buckler'
  | 'Corsair Sword'
  | 'Corundum Flask'
  | 'Courtesan Sword'
  | 'Courthouse Map'
  | 'Courtyard Map'
  | 'Coves Map'
  | 'Crack Mace'
  | 'Crater Map'
  | 'Crescent Staff'
  | 'Crested Tower Shield'
  | 'Crimson Jewel'
  | 'Crimson Raiment'
  | 'Crimson Round Shield'
  | 'Crimson Temple Map'
  | 'Crimson Township Map'
  | 'Crude Bow'
  | 'Crude Sensing Charm'
  | 'Crude Ward'
  | 'Crusader Boots'
  | 'Crusader Buckler'
  | 'Crusader Chainmail'
  | 'Crusader Gloves'
  | 'Crusader Helmet'
  | 'Crusader Plate'
  | 'Crushing Force Magnifier'
  | 'Crypt Armour'
  | 'Crystal Belt'
  | 'Crystal Ore Map'
  | 'Crystal Sceptre'
  | 'Crystal Wand'
  | 'Cursed Crypt Map'
  | 'Curved Blade'
  | 'Cutlass'
  | "Cutthroat's Garb"
  | 'Dagger Axe'
  | 'Dark Forest Map'
  | 'Darksteel Treads'
  | 'Darkwood Sceptre'
  | 'Deadhand Talisman'
  | 'Death Bow'
  | 'Debilitation Gauntlets'
  | 'Decimation Bow'
  | 'Decorative Axe'
  | 'Decurve Bow'
  | 'Deep One Talisman'
  | 'Deerskin Boots'
  | 'Deerskin Gloves'
  | 'Defiled Cathedral Map'
  | 'Deicide Mask'
  | 'Demon Crown'
  | 'Demon Dagger'
  | "Demon's Horn"
  | 'Desert Brigandine'
  | 'Desert Map'
  | 'Desert Spring Map'
  | 'Despot Axe'
  | 'Destiny Leather'
  | 'Destroyer Regalia'
  | 'Devout Chainmail'
  | 'Diamond Flask'
  | 'Diamond Ring'
  | 'Dig Map'
  | 'Disapprobation Axe'
  | 'Divine Life Flask'
  | 'Divine Mana Flask'
  | 'Double Axe'
  | 'Double Claw'
  | 'Dragon Mace'
  | 'Dragonbone Rapier'
  | 'Dragonscale Boots'
  | 'Dragonscale Doublet'
  | 'Dragonscale Gauntlets'
  | 'Dragoon Sword'
  | 'Dread Maul'
  | 'Dream Mace'
  | 'Dreamquest Slippers'
  | 'Driftwood Club'
  | 'Driftwood Maul'
  | 'Driftwood Sceptre'
  | 'Driftwood Spiked Shield'
  | 'Driftwood Wand'
  | 'Dry Sea Map'
  | 'Dunes Map'
  | 'Dungeon Map'
  | 'Dusk Blade'
  | 'Dusk Ring'
  | 'Duskwalk Slippers'
  | 'Eagle Claw'
  | 'Ebony Tower Shield'
  | 'Eclipse Staff'
  | 'Eelskin Boots'
  | 'Eelskin Gloves'
  | 'Eelskin Sole'
  | 'Eelskin Tunic'
  | "Einhar's Memory"
  | 'Elder Sword'
  | 'Elegant Foil'
  | 'Elegant Ringmail'
  | 'Elegant Round Shield'
  | 'Elegant Sword'
  | 'Embroidered Gloves'
  | 'Enamel Brooch'
  | 'Enameled Buckler'
  | 'Endothermic Buckler'
  | 'Engraved Greatsword'
  | 'Engraved Hatchet'
  | 'Engraved Wand'
  | 'Espionage Disguise Kit'
  | 'Essential Keyring'
  | 'Estoc'
  | 'Estuary Map'
  | 'Etched Greatsword'
  | 'Etched Hatchet'
  | 'Etched Kite Shield'
  | 'Eternal Burgonet'
  | 'Eternal Life Flask'
  | 'Eternal Mana Flask'
  | 'Eternal Sword'
  | 'Eventuality Rod'
  | 'Excavation Map'
  | 'Exhausting Spirit Shield'
  | 'Exothermic Tower Shield'
  | 'Expedition Logbook'
  | 'Exquisite Blade'
  | 'Exquisite Leather'
  | 'Eye Gouger'
  | 'Ezomyte Axe'
  | 'Ezomyte Blade'
  | 'Ezomyte Burgonet'
  | 'Ezomyte Dagger'
  | 'Ezomyte Spiked Shield'
  | 'Ezomyte Staff'
  | 'Ezomyte Tower Shield'
  | 'Factory Map'
  | 'Familial Contract'
  | 'Fancy Foil'
  | 'Fangjaw Talisman'
  | "Faun's Horn"
  | 'Feathered Arrow Quiver'
  | 'Fencer Helm'
  | 'Festival Mask'
  | 'Fickle Spiritblade'
  | 'Field Lamellar'
  | 'Fields Map'
  | 'Fiend Dagger'
  | 'Fine Lockpick'
  | 'Fine Sensing Charm'
  | 'Fine Sharpening Stone'
  | 'Fingerless Silk Gloves'
  | 'Fir Round Shield'
  | 'Fire Arrow Quiver'
  | 'Fishing Rod'
  | 'Fishscale Gauntlets'
  | 'Flanged Arrowhead'
  | 'Flanged Drill'
  | 'Flanged Mace'
  | 'Flare Mace'
  | 'Flashfire Blade'
  | 'Flaying Knife'
  | 'Fleshripper'
  | 'Flickerflame Blade'
  | 'Flooded Mine Map'
  | 'Fluted Bascinet'
  | 'Focal Stone'
  | 'Foliate Brooch'
  | 'Footman Sword'
  | 'Forbidden Woods Map'
  | 'Forge of the Phoenix Map'
  | 'Forking River Map'
  | 'Fossilised Spirit Shield'
  | 'Foul Staff'
  | 'Foundry Bow'
  | 'Foundry Map'
  | 'Foxhide Sole'
  | 'Fragmenting Arrowhead'
  | 'Fright Claw'
  | 'Fright Maul'
  | 'Frontier Leather'
  | 'Frozen Cabins Map'
  | 'Fugitive Boots'
  | 'Full Chainmail'
  | 'Full Dragonscale'
  | 'Full Leather'
  | 'Full Plate'
  | 'Full Ringmail'
  | 'Full Scale Armour'
  | 'Full Wyrmscale'
  | 'Fungal Hollow Map'
  | 'Gale Crown'
  | 'Gardens Map'
  | 'Gauche Gloves'
  | 'Gavel'
  | 'Gemini Claw'
  | 'Gemstone Sword'
  | "General's Brigandine"
  | 'Geode Map'
  | 'Geodesic Ring'
  | 'Ghastly Eye Jewel'
  | 'Ghetto Map'
  | 'Giant Life Flask'
  | 'Giant Mana Flask'
  | 'Gilded Axe'
  | 'Gilded Buckler'
  | 'Gilded Sallet'
  | 'Girded Tower Shield'
  | 'Glacier Map'
  | 'Gladiator Helmet'
  | 'Gladiator Plate'
  | 'Gladius'
  | 'Glass Shank'
  | 'Gloam Ring'
  | 'Glorious Leather'
  | 'Glorious Plate'
  | 'Gnarled Branch'
  | 'Goathide Boots'
  | 'Goathide Buckler'
  | 'Goathide Gloves'
  | 'Gold Amulet'
  | 'Gold Flask'
  | 'Gold Ring'
  | 'Golden Brooch'
  | 'Golden Buckler'
  | 'Golden Kris'
  | 'Golden Mask'
  | 'Golden Plate'
  | 'Goliath Gauntlets'
  | 'Goliath Greaves'
  | 'Gouger'
  | 'Graceful Sword'
  | 'Grand Life Flask'
  | 'Grand Mana Flask'
  | 'Grandmaster Keyring'
  | 'Granite Flask'
  | 'Grappler'
  | 'Grasping Mail'
  | 'Grave Trough Map'
  | 'Graveyard Map'
  | 'Great Crown'
  | 'Great Helmet'
  | 'Great Mallet'
  | 'Great White Claw'
  | 'Greater Life Flask'
  | 'Greater Mana Flask'
  | 'Greatwolf Talisman'
  | 'Grinning Fetish'
  | 'Gripped Gloves'
  | 'Grotto Map'
  | 'Grove Bow'
  | 'Gruelling Gauntlets'
  | 'Gut Ripper'
  | 'Gutting Knife'
  | 'Hallowed Hybrid Flask'
  | 'Hallowed Life Flask'
  | 'Hallowed Mana Flask'
  | 'Hammered Buckler'
  | 'Harbinger Bow'
  | 'Harbinger Map'
  | 'Harlequin Mask'
  | 'Harmonic Spirit Shield'
  | 'Harpy Rapier'
  | 'Haunted Mansion Map'
  | "Headman's Sword"
  | 'Headsman Axe'
  | 'Heat-attuned Tower Shield'
  | 'Heathen Wand'
  | 'Heavy Arrow Quiver'
  | 'Heavy Belt'
  | 'Hedron Bow'
  | "Hellion's Paw"
  | 'Hexclaw Talisman'
  | 'Highborn Bow'
  | 'Highborn Staff'
  | 'Highland Blade'
  | 'Hollowpoint Arrowhead'
  | 'Hollowpoint Dagger'
  | 'Holy Chainmail'
  | 'Honed Cleaver'
  | 'Hooded Cloak'
  | 'Hook Sword'
  | 'Horned Sceptre'
  | 'Horned Talisman'
  | 'Hubris Circlet'
  | 'Hunter Hood'
  | 'Hussar Brigandine'
  | 'Hydrascale Boots'
  | 'Hydrascale Gauntlets'
  | 'Hypnotic Eye Jewel'
  | 'Iceberg Map'
  | 'Imbued Wand'
  | 'Imp Crown'
  | 'Imp Dagger'
  | 'Impact Force Propagator'
  | 'Imperial Bow'
  | 'Imperial Buckler'
  | 'Imperial Claw'
  | 'Imperial Maul'
  | 'Imperial Skean'
  | 'Imperial Staff'
  | 'Imperial Staff Piece'
  | 'Incandescent Invitation'
  | 'Infantry Brigandine'
  | 'Infernal Axe'
  | 'Infernal Blade'
  | 'Infernal Sword'
  | 'Infested Valley Map'
  | 'Iolite Ring'
  | 'Iron Circlet'
  | 'Iron Flask'
  | 'Iron Gauntlets'
  | 'Iron Greaves'
  | 'Iron Hat'
  | 'Iron Mask'
  | 'Iron Ring'
  | 'Iron Sceptre'
  | 'Iron Staff'
  | 'Ironscale Boots'
  | 'Ironscale Gauntlets'
  | 'Ironwood Buckler'
  | 'Ivory Bow'
  | 'Ivory Spirit Shield'
  | 'Ivory Temple Map'
  | 'Jade Amulet'
  | 'Jade Chopper'
  | 'Jade Flask'
  | 'Jade Hatchet'
  | 'Jagged Foil'
  | 'Jagged Maul'
  | 'Jasper Axe'
  | 'Jasper Chopper'
  | 'Jewelled Foil'
  | 'Jingling Spirit Shield'
  | 'Judgement Staff'
  | 'Jungle Valley Map'
  | 'Karui Axe'
  | 'Karui Chopper'
  | 'Karui Maul'
  | 'Karui Sceptre'
  | "Kirac's Memory"
  | 'Laboratory Map'
  | 'Labrys'
  | 'Lacewood Spirit Shield'
  | 'Lacquered Buckler'
  | 'Lacquered Garb'
  | 'Lacquered Helmet'
  | 'Lair Map'
  | 'Lair of the Hydra Map'
  | 'Laminated Kite Shield'
  | 'Lapis Amulet'
  | 'Large Cluster Jewel'
  | 'Large Hybrid Flask'
  | 'Large Life Flask'
  | 'Large Mana Flask'
  | 'Lathi'
  | 'Latticed Ringmail'
  | 'Lava Chamber Map'
  | 'Lava Lake Map'
  | 'Layered Kite Shield'
  | 'Lead Sceptre'
  | 'Leather Belt'
  | 'Leather Bracers'
  | 'Leather Cap'
  | 'Leather Hood'
  | 'Leatherscale Boots'
  | 'Legion Boots'
  | 'Legion Gloves'
  | 'Legion Hammer'
  | 'Legion Sword'
  | 'Legion Sword Piece'
  | 'Leyline Gloves'
  | 'Leyline Map'
  | 'Light Brigandine'
  | 'Lighthouse Map'
  | 'Linden Kite Shield'
  | 'Lion Pelt'
  | 'Lion Sword'
  | 'Lithe Blade'
  | 'Lone Antler Talisman'
  | 'Long Bow'
  | 'Long Staff'
  | 'Longsword'
  | 'Longtooth Talisman'
  | 'Lookout Map'
  | 'Lordly Plate'
  | 'Loricated Ringmail'
  | 'Lunaris Circlet'
  | 'Lustrous Ward'
  | 'Maelström Staff'
  | "Mage's Vestment"
  | 'Magistrate Crown'
  | 'Magmatic Tower Shield'
  | 'Mahogany Tower Shield'
  | 'Majestic Plate'
  | 'Malformation Map'
  | 'Malign Fangs'
  | 'Mallet'
  | 'Maltreatment Axe'
  | 'Mandible Talisman'
  | 'Maple Round Shield'
  | 'Maraketh Bow'
  | 'Marble Amulet'
  | 'Marshes Map'
  | 'Master Lockpick'
  | 'Mausoleum Map'
  | "Maven's Invitation: The Atlas"
  | "Maven's Invitation: The Elderslayers"
  | "Maven's Invitation: The Feared"
  | "Maven's Invitation: The Forgotten"
  | "Maven's Invitation: The Formed"
  | "Maven's Invitation: The Hidden"
  | "Maven's Invitation: The Twisted"
  | 'Maze Map'
  | 'Maze of the Minotaur Map'
  | 'Meatgrinder'
  | 'Mechalarm Belt'
  | 'Medium Cluster Jewel'
  | 'Medium Hybrid Flask'
  | 'Medium Life Flask'
  | 'Medium Mana Flask'
  | 'Mesa Map'
  | 'Mesh Boots'
  | 'Mesh Gloves'
  | 'Micro-Distillery Belt'
  | 'Midnight Blade'
  | 'Military Staff'
  | 'Mind Cage'
  | 'Mineral Pools Map'
  | 'Mirrored Spiked Shield'
  | 'Monkey Paw Talisman'
  | 'Monkey Twins Talisman'
  | 'Moon Staff'
  | 'Moon Temple Map'
  | 'Moonstone Ring'
  | 'Morning Star'
  | 'Mosaic Kite Shield'
  | 'Mud Geyser Map'
  | 'Murder Boots'
  | 'Murder Mitts'
  | 'Murderous Eye Jewel'
  | 'Museum Map'
  | 'Nailed Fist'
  | 'Naval Contract'
  | 'Necromancer Circlet'
  | 'Necromancer Silks'
  | 'Necropolis Map'
  | 'Nexus Gloves'
  | 'Nightmare Bascinet'
  | 'Nightmare Mace'
  | 'Nightwind Slippers'
  | "Niko's Memory"
  | 'Noble Axe'
  | 'Noble Claw'
  | 'Noble Tricorne'
  | 'Nubuck Boots'
  | 'Nubuck Gloves'
  | 'Oak Buckler'
  | 'Obsidian Sharpening Stone'
  | "Occultist's Vestment"
  | 'Ochre Sceptre'
  | 'Oiled Coat'
  | 'Oiled Vest'
  | 'Omen Wand'
  | 'Onyx Amulet'
  | 'Opal Ring'
  | 'Opal Sceptre'
  | 'Opal Wand'
  | 'Orchard Map'
  | 'Ornate Mace'
  | 'Ornate Quiver'
  | 'Ornate Ringmail'
  | 'Ornate Spiked Shield'
  | 'Ornate Sword'
  | 'Oscillating Sceptre'
  | 'Overgrown Ruin Map'
  | 'Overgrown Shrine Map'
  | 'Padded Jacket'
  | 'Padded Vest'
  | 'Pagan Wand'
  | 'Painted Buckler'
  | 'Painted Tower Shield'
  | 'Palace Map'
  | 'Papyrus Relic'
  | 'Park Map'
  | 'Paua Amulet'
  | 'Paua Ring'
  | 'Pecoraro'
  | 'Pen Map'
  | 'Penetrating Arrow Quiver'
  | 'Peninsula Map'
  | 'Penitent Mask'
  | 'Penumbra Ring'
  | 'Pernach'
  | 'Petrified Club'
  | 'Phantasmagoria Map'
  | 'Phantom Mace'
  | 'Pier Map'
  | 'Pig-Faced Bascinet'
  | 'Piledriver'
  | 'Pine Buckler'
  | 'Pinnacle Tower Shield'
  | 'Pit Map'
  | 'Pit of the Chimera Map'
  | 'Plague Mask'
  | 'Plank Kite Shield'
  | 'Plate Vest'
  | 'Plateau Map'
  | 'Plated Gauntlets'
  | 'Plated Greaves'
  | 'Plated Maul'
  | 'Platinum Kris'
  | 'Platinum Sceptre'
  | 'Plaza Map'
  | 'Pneumatic Dagger'
  | 'Poignard'
  | 'Polar Buckler'
  | 'Polaric Invitation'
  | 'Poleaxe'
  | 'Polished Sensing Charm'
  | 'Polished Spiked Shield'
  | 'Port Map'
  | 'Potentiality Rod'
  | 'Praetor Crown'
  | 'Precinct Map'
  | 'Precise Arrowhead'
  | 'Prehistoric Claw'
  | 'Pressurised Dagger'
  | 'Preventative Contract'
  | 'Primal Arrow Quiver'
  | 'Primal Skull Talisman'
  | 'Prime Cleaver'
  | 'Primeval Rapier'
  | 'Primitive Staff'
  | 'Primordial Blocks Map'
  | 'Primordial Pool Map'
  | 'Primordial Staff'
  | 'Prismatic Jewel'
  | 'Prismatic Ring'
  | 'Processional Relic'
  | 'Profane Wand'
  | 'Promenade Map'
  | 'Prong Dagger'
  | 'Prophecy Wand'
  | 'Prophet Crown'
  | 'Psychotic Axe'
  | 'Quarterstaff'
  | 'Quartz Flask'
  | 'Quartz Sceptre'
  | 'Quartz Wand'
  | 'Quicksilver Flask'
  | 'Quilted Jacket'
  | 'Racecourse Map'
  | 'Ramparts Map'
  | 'Ranger Bow'
  | 'Raven Mask'
  | 'Rawhide Boots'
  | 'Rawhide Gloves'
  | 'Rawhide Tower Shield'
  | 'Reaver Axe'
  | 'Reaver Helmet'
  | 'Reaver Sword'
  | 'Rebuking Blade'
  | 'Reciprocation Staff'
  | 'Recurve Bow'
  | 'Redwood Spiked Shield'
  | 'Reef Map'
  | 'Reflex Bow'
  | 'Regicide Disguise Kit'
  | 'Regicide Mask'
  | 'Reinforced Greaves'
  | 'Reinforced Kite Shield'
  | 'Reinforced Tower Shield'
  | 'Relic Chambers Map'
  | 'Residence Map'
  | 'Ring'
  | 'Ringmail Boots'
  | 'Ringmail Coat'
  | 'Ringmail Gloves'
  | 'Ritual Sceptre'
  | 'Riveted Boots'
  | 'Riveted Gloves'
  | 'Rock Breaker'
  | 'Rot Head Talisman'
  | 'Rotfeather Talisman'
  | 'Rotted Round Shield'
  | 'Rough Sharpening Stone'
  | 'Royal Axe'
  | 'Royal Bow'
  | 'Royal Burgonet'
  | 'Royal Sceptre'
  | 'Royal Skean'
  | 'Royal Staff'
  | 'Ruby Flask'
  | 'Ruby Ring'
  | 'Runed Bracers'
  | 'Runic Crest'
  | 'Runic Crown'
  | 'Runic Gages'
  | 'Runic Gauntlets'
  | 'Runic Gloves'
  | 'Runic Greaves'
  | 'Runic Hatchet'
  | 'Runic Helm'
  | 'Runic Sabatons'
  | 'Runic Sollerets'
  | 'Rusted Coif'
  | 'Rusted Hatchet'
  | 'Rusted Spike'
  | 'Rusted Sword'
  | 'Rustic Sash'
  | 'Sabre'
  | 'Sacred Hybrid Flask'
  | 'Sacred Life Flask'
  | 'Sacred Mana Flask'
  | 'Sacrificial Garb'
  | 'Sadist Garb'
  | 'Sage Wand'
  | "Sage's Robe"
  | 'Sai'
  | "Saint's Hauberk"
  | 'Saintly Chainmail'
  | 'Sallet'
  | 'Sambar Sceptre'
  | 'Samite Gloves'
  | 'Samite Slippers'
  | 'Samnite Helmet'
  | 'Sanctified Life Flask'
  | 'Sanctified Mana Flask'
  | 'Sapphire Flask'
  | 'Sapphire Ring'
  | 'Satin Gloves'
  | 'Satin Slippers'
  | "Savant's Robe"
  | 'Scale Doublet'
  | 'Scale Vest'
  | 'Scare Mask'
  | 'Scarlet Raiment'
  | 'Scarlet Round Shield'
  | 'Scholar Boots'
  | "Scholar's Robe"
  | 'Screaming Invitation'
  | 'Scriptorium Map'
  | 'Seaglass Amulet'
  | 'Searching Eye Jewel'
  | 'Secutor Helm'
  | 'Sekhem'
  | 'Sentinel Jacket'
  | 'Sepulchre Map'
  | 'Serpentine Staff'
  | 'Serpentscale Boots'
  | 'Serpentscale Gauntlets'
  | 'Serrated Arrow Quiver'
  | 'Serrated Foil'
  | 'Shabby Jerkin'
  | 'Shackled Boots'
  | 'Shadow Axe'
  | 'Shadow Fangs'
  | 'Shadow Sceptre'
  | 'Shadowed Ring'
  | 'Shagreen Boots'
  | 'Shagreen Gloves'
  | 'Shagreen Tower Shield'
  | 'Sharkskin Boots'
  | 'Sharkskin Gloves'
  | 'Sharkskin Tunic'
  | 'Sharktooth Arrow Quiver'
  | 'Sharktooth Claw'
  | 'Shining Ward'
  | 'Shipyard Map'
  | 'Shore Map'
  | 'Short Bow'
  | 'Shrine Map'
  | 'Siege Axe'
  | 'Siege Helmet'
  | 'Siege Map'
  | 'Silk Gloves'
  | 'Silk Robe'
  | 'Silk Slippers'
  | 'Silken Garb'
  | 'Silken Hood'
  | 'Silken Vest'
  | 'Silken Wrap'
  | 'Silkweave Sole'
  | 'Silo Map'
  | 'Silver Brooch'
  | 'Silver Flask'
  | 'Simple Lockpick'
  | 'Simple Robe'
  | 'Simplex Amulet'
  | 'Sinistral Gloves'
  | 'Sinner Tricorne'
  | 'Skean'
  | 'Skeleton Keyring'
  | 'Skinning Knife'
  | 'Slaughter Knife'
  | 'Sledgehammer'
  | 'Sleek Coat'
  | 'Slink Boots'
  | 'Slink Gloves'
  | 'Small Cluster Jewel'
  | 'Small Hybrid Flask'
  | 'Small Life Flask'
  | 'Small Mana Flask'
  | 'Smallsword'
  | 'Sniper Bow'
  | 'Solar Maul'
  | 'Solarine Bow'
  | 'Solaris Circlet'
  | 'Soldier Boots'
  | 'Soldier Gloves'
  | 'Soldier Helmet'
  | "Soldier's Brigandine"
  | 'Sorcerer Boots'
  | 'Sorcerer Gloves'
  | 'Sorrow Mask'
  | 'Southswing Gloves'
  | 'Sovereign Spiked Shield'
  | 'Sparkling Claw'
  | 'Spectral Axe'
  | 'Spectral Sword'
  | 'Spider Forest Map'
  | 'Spider Lair Map'
  | 'Spidersilk Robe'
  | 'Spike-Point Arrow Quiver'
  | 'Spiked Bundle'
  | 'Spiked Club'
  | 'Spiked Gloves'
  | 'Spiked Round Shield'
  | 'Spine Bow'
  | 'Spinefuse Talisman'
  | 'Spiny Maul'
  | 'Spiny Round Shield'
  | 'Spiraled Foil'
  | 'Spiraled Wand'
  | 'Splendid Round Shield'
  | 'Splintered Tower Shield'
  | 'Splitnewt Talisman'
  | 'Stabilising Sceptre'
  | 'Stag Sceptre'
  | 'Stagnation Map'
  | 'Standard Lockpick'
  | 'Standard Sharpening Stone'
  | 'Stealth Boots'
  | 'Stealth Gloves'
  | 'Steel Bracers'
  | 'Steel Circlet'
  | 'Steel Drill'
  | 'Steel Gauntlets'
  | 'Steel Greaves'
  | 'Steel Kite Shield'
  | 'Steel Ring'
  | 'Steelhead'
  | 'Steelscale Boots'
  | 'Steelscale Gauntlets'
  | 'Steelwood Bow'
  | 'Stibnite Flask'
  | 'Stiletto'
  | 'Stone Axe'
  | 'Stone Hammer'
  | 'Stormrider Boots'
  | 'Strand Map'
  | 'Strapped Boots'
  | 'Strapped Leather'
  | 'Strapped Mitts'
  | 'Studded Belt'
  | 'Studded Bracers'
  | 'Studded Round Shield'
  | 'Stygian Vise'
  | 'Subsuming Spirit Shield'
  | 'Sulphur Blowtorch'
  | 'Sulphur Flask'
  | 'Sulphur Vents Map'
  | 'Summit Map'
  | 'Sun Leather'
  | 'Sun Plate'
  | 'Sundering Axe'
  | 'Sunken City Map'
  | 'Supreme Spiked Shield'
  | 'Synthesised Map'
  | 'Talon Axe'
  | 'Tarnished Spirit Shield'
  | 'Tattered Cloak'
  | 'Taxing Gauntlets'
  | 'Teak Round Shield'
  | 'Tempered Foil'
  | 'Temple Map'
  | 'Tenderizer'
  | 'Tenebrous Ring'
  | 'Terrace Map'
  | 'Terror Claw'
  | 'Terror Maul'
  | 'Thaumaturgical Sensing Charm'
  | 'Thaumaturgical Ward'
  | 'Thaumetic Blowtorch'
  | 'Thaumetic Flashpowder'
  | 'Theatre Disguise Kit'
  | 'Thicket Bow'
  | 'Thicket Map'
  | "Thief's Garb"
  | "Thief's Trinket"
  | 'Thorium Spirit Shield'
  | 'Thorn Rapier'
  | 'Three Hands Talisman'
  | 'Three Rat Talisman'
  | 'Thresher Claw'
  | 'Throat Stabber'
  | 'Tiger Hook'
  | 'Tiger Sword'
  | "Tiger's Paw"
  | 'Timber Axe'
  | 'Timeless Jewel'
  | 'Timeworn Claw'
  | 'Titan Gauntlets'
  | 'Titan Greaves'
  | 'Titanium Spirit Shield'
  | 'Tomahawk'
  | 'Tome Relic'
  | 'Topaz Flask'
  | 'Topaz Ring'
  | 'Torn Cloak'
  | 'Tornado Wand'
  | 'Torture Cage'
  | 'Totemic Maul'
  | 'Tower Map'
  | 'Toxic Sewer Map'
  | 'Transfer-attuned Spirit Shield'
  | 'Transformer Staff'
  | 'Trapper Boots'
  | 'Trapper Mitts'
  | 'Trarthan Flashpowder'
  | 'Tribal Circlet'
  | 'Tribal Club'
  | 'Tribal Maul'
  | 'Tricorne'
  | 'Trisula'
  | 'Triumphant Lamellar'
  | 'Tropical Island Map'
  | 'Turquoise Amulet'
  | 'Twig Spirit Shield'
  | 'Twilight Blade'
  | 'Twin Claw'
  | 'Two-Handed Sword'
  | 'Two-Point Arrow Quiver'
  | 'Two-Stone Ring'
  | 'Two-Toned Boots'
  | "Tyrant's Sekhem"
  | 'Ultimatum Aspect'
  | 'Underground River Map'
  | 'Underground Sea Map'
  | 'Undying Flesh Talisman'
  | 'Unset Amulet'
  | 'Unset Ring'
  | 'Urn Relic'
  | 'Ursine Pelt'
  | 'Vaal Axe'
  | 'Vaal Blade'
  | 'Vaal Buckler'
  | 'Vaal Claw'
  | 'Vaal Gauntlets'
  | 'Vaal Greatsword'
  | 'Vaal Greaves'
  | 'Vaal Hatchet'
  | 'Vaal Mask'
  | 'Vaal Pyramid Map'
  | 'Vaal Rapier'
  | 'Vaal Regalia'
  | 'Vaal Sceptre'
  | 'Vaal Spirit Shield'
  | 'Vaal Temple Map'
  | 'Vanguard Belt'
  | 'Variscite Blade'
  | 'Varnished Coat'
  | 'Vault Map'
  | 'Velvet Gloves'
  | 'Velvet Slippers'
  | 'Vengeful Contract'
  | 'Vermillion Ring'
  | 'Versatile Keyring'
  | 'Vigilante Contract'
  | 'Vile Arrow Quiver'
  | 'Vile Staff'
  | 'Villa Map'
  | 'Vine Circlet'
  | 'Viridian Jewel'
  | 'Visored Sallet'
  | 'Void Axe'
  | 'Void Fangs'
  | 'Void Sceptre'
  | 'Volcano Map'
  | 'Voltaxic Flashpowder'
  | 'Walnut Spirit Shield'
  | 'War Axe'
  | 'War Buckler'
  | 'War Hammer'
  | 'War Plate'
  | 'War Sword'
  | 'Waste Pool Map'
  | 'Wasteland Map'
  | 'Waterways Map'
  | 'Waxed Garb'
  | 'Wereclaw Talisman'
  | 'Whalebone Rapier'
  | 'Wharf Map'
  | 'Whisper-woven Cloak'
  | 'Widowsilk Robe'
  | 'Wild Leather'
  | 'Windbreak Boots'
  | 'Winged Sole'
  | 'Winter Crown'
  | 'Wolf Pelt'
  | 'Woodful Staff'
  | 'Woodsplitter'
  | 'Wool Gloves'
  | 'Wool Shoes'
  | 'Wraith Axe'
  | 'Wraith Sword'
  | 'Wrapped Boots'
  | 'Wrapped Mitts'
  | 'Wrist Chopper'
  | 'Writhing Invitation'
  | 'Writhing Talisman'
  | 'Wyrm Mace'
  | 'Wyrmbone Rapier'
  | 'Wyrmscale Boots'
  | 'Wyrmscale Doublet'
  | 'Wyrmscale Gauntlets'
  | 'Yew Spirit Shield'
  | 'Zealot Boots'
  | 'Zealot Gloves'
  | 'Zealot Helmet'
  | 'Zodiac Leather'
  | 'Abrasive Catalyst'
  | 'Accelerating Catalyst'
  | 'Albino Rhoa Feather'
  | 'Alchemy Shard'
  | 'Alteration Shard'
  | 'Ancient Orb'
  | 'Ancient Shard'
  | 'Annulment Shard'
  | "Armourer's Scrap"
  | 'Astragali'
  | 'Awakened Sextant'
  | "Awakener's Orb"
  | 'Bestiary Orb'
  | 'Binding Shard'
  | "Blacksmith's Whetstone"
  | 'Blessed Orb'
  | 'Blessing of Chayula'
  | 'Blessing of Esh'
  | 'Blessing of Tul'
  | 'Blessing of Uul-Netol'
  | 'Blessing of Xoph'
  | 'Blighted Scouting Report'
  | 'Burial Medallion'
  | "Cartographer's Chisel"
  | 'Chaos Orb'
  | 'Chaos Shard'
  | 'Charged Compass'
  | 'Chromatic Orb'
  | 'Comprehensive Scouting Report'
  | 'Crescent Splinter'
  | "Crusader's Exalted Orb"
  | 'Delirious Scouting Report'
  | 'Divine Orb'
  | 'Eldritch Chaos Orb'
  | 'Eldritch Exalted Orb'
  | 'Eldritch Orb of Annulment'
  | 'Elevated Sextant'
  | "Engineer's Orb"
  | "Engineer's Shard"
  | 'Enkindling Orb'
  | 'Eternal Orb'
  | 'Exalted Orb'
  | 'Exalted Shard'
  | 'Exceptional Eldritch Ember'
  | 'Exceptional Eldritch Ichor'
  | 'Exotic Coinage'
  | "Explorer's Scouting Report"
  | "Facetor's Lens"
  | 'Fertile Catalyst'
  | 'Fracturing Orb'
  | 'Fracturing Shard'
  | "Gemcutter's Prism"
  | "Glassblower's Bauble"
  | 'Grand Eldritch Ember'
  | 'Grand Eldritch Ichor'
  | 'Greater Eldritch Ember'
  | 'Greater Eldritch Ichor'
  | "Harbinger's Orb"
  | "Harbinger's Shard"
  | 'Horizon Shard'
  | "Hunter's Exalted Orb"
  | 'Imbued Catalyst'
  | 'Influenced Scouting Report'
  | 'Instilling Orb'
  | 'Intrinsic Catalyst'
  | "Jeweller's Orb"
  | 'Lesser Eldritch Ember'
  | 'Lesser Eldritch Ichor'
  | 'Mirror Shard'
  | 'Mirror of Kalandra'
  | 'Noxious Catalyst'
  | 'Oil Extractor'
  | "Operative's Scouting Report"
  | 'Orb of Alchemy'
  | 'Orb of Alteration'
  | 'Orb of Annulment'
  | 'Orb of Augmentation'
  | 'Orb of Binding'
  | 'Orb of Chance'
  | 'Orb of Conflict'
  | 'Orb of Dominance'
  | 'Orb of Fusing'
  | 'Orb of Horizons'
  | 'Orb of Regret'
  | 'Orb of Scouring'
  | 'Orb of Transmutation'
  | 'Orb of Unmaking'
  | 'Otherworldly Scouting Report'
  | 'Portal Scroll'
  | 'Primal Crystallised Lifeforce'
  | 'Prime Regrading Lens'
  | 'Prismatic Catalyst'
  | "Redeemer's Exalted Orb"
  | 'Regal Orb'
  | 'Regal Shard'
  | 'Ritual Splinter'
  | 'Ritual Vessel'
  | 'Sacred Crystallised Lifeforce'
  | 'Sacred Orb'
  | 'Scrap Metal'
  | 'Scroll of Wisdom'
  | 'Secondary Regrading Lens'
  | 'Singular Scouting Report'
  | 'Stacked Deck'
  | "Surveyor's Compass"
  | 'Tailoring Orb'
  | "Tainted Armourer's Scrap"
  | "Tainted Blacksmith's Whetstone"
  | 'Tainted Blessing'
  | 'Tainted Chaos Orb'
  | 'Tainted Chromatic Orb'
  | 'Tainted Divine Teardrop'
  | 'Tainted Exalted Orb'
  | "Tainted Jeweller's Orb"
  | 'Tainted Mythic Orb'
  | 'Tainted Orb of Fusing'
  | 'Tempering Catalyst'
  | 'Tempering Orb'
  | 'Transmutation Shard'
  | 'Turbulent Catalyst'
  | 'Unstable Catalyst'
  | 'Vaal Orb'
  | 'Vaal Scouting Report'
  | 'Veiled Chaos Orb'
  | 'Vivid Crystallised Lifeforce'
  | "Warlord's Exalted Orb"
  | 'Wild Crystallised Lifeforce'
  | 'A Chilling Wind'
  | 'A Dab of Ink'
  | 'A Dusty Memory'
  | 'A Familiar Call'
  | 'A Fate Worse Than Death'
  | 'A Modest Request'
  | "A Mother's Parting Gift"
  | 'A Note in the Wind'
  | 'A Sea of Blue'
  | 'A Stone Perfected'
  | 'Abandoned Wealth'
  | 'Acclimatisation'
  | "Akil's Prophecy"
  | "Alivia's Grace"
  | 'Alluring Bounty'
  | 'Alone in the Darkness'
  | 'Altered Perception'
  | 'Ambitious Obsession'
  | "Anarchy's Price"
  | 'Arrogance of the Vaal'
  | "Assassin's Favour"
  | 'Astral Protection'
  | "Atziri's Arsenal"
  | 'Audacity'
  | 'Auspicious Ambitions'
  | 'Azure Rage'
  | "Azyran's Reward"
  | 'Baited Expectations'
  | 'Beauty Through Death'
  | 'Bijoux'
  | 'Blind Venture'
  | 'Boon of Justice'
  | 'Boon of the First Ones'
  | 'Boundless Realms'
  | "Bowyer's Dream"
  | 'Broken Promises'
  | 'Broken Truce'
  | "Brother's Gift"
  | "Brother's Stash"
  | 'Brotherhood in Exile'
  | 'Brush, Paint and Palette'
  | 'Buried Treasure'
  | 'Burning Blood'
  | 'Call to the First Ones'
  | "Cameria's Cut"
  | "Cartographer's Delight"
  | 'Chaotic Disposition'
  | 'Chasing Risk'
  | 'Checkmate'
  | 'Choking Guilt'
  | 'Costly Curio'
  | 'Council of Cats'
  | 'Coveted Possession'
  | 'Cursed Words'
  | 'Dark Dreams'
  | 'Dark Temptation'
  | 'Darker Half'
  | 'Deadly Joy'
  | 'Death'
  | 'Deathly Designs'
  | 'Dementophobia'
  | "Demigod's Wager"
  | 'Desecrated Virtue'
  | 'Desperate Crusade'
  | 'Destined to Crumble'
  | "Dialla's Subjugation"
  | 'Disdain'
  | 'Divine Beauty'
  | 'Divine Justice'
  | "Doedre's Madness"
  | "Doryani's Epiphany"
  | 'Draped in Dreams'
  | 'Duality'
  | 'Dying Anguish'
  | 'Dying Light'
  | 'Earth Drinker'
  | 'Echoes of Love'
  | 'Emperor of Purity'
  | "Emperor's Luck"
  | 'Endless Night'
  | 'Etched in Blood'
  | 'Eternal Bonds'
  | 'Ever-Changing'
  | 'Fateful Meeting'
  | 'Fire Of Unknown Origin'
  | 'Forbidden Power'
  | 'From Bone to Ashes'
  | 'Further Invention'
  | "Gemcutter's Mercy"
  | "Gemcutter's Promise"
  | 'Gift of Asenath'
  | 'Gift of the Gemling Queen'
  | 'Glimmer of Hope'
  | 'Grave Knowledge'
  | "Guardian's Challenge"
  | 'Harmony of Souls'
  | 'Haunting Shadows'
  | 'Her Mask'
  | 'Heterochromia'
  | 'Home'
  | 'Hope'
  | 'House of Mirrors'
  | 'Hubris'
  | 'Humility'
  | "Hunter's Resolve"
  | "Hunter's Reward"
  | 'Immortal Resolve'
  | 'Imperfect Memories'
  | 'Imperial Legacy'
  | 'Jack in the Box'
  | 'Judging Voices'
  | 'Justified Ambition'
  | "Keeper's Corruption"
  | 'Lachrymal Necrosis'
  | "Lantador's Lost Love"
  | 'Last Hope'
  | 'Left to Fate'
  | 'Lethean Temptation'
  | 'Light and Truth'
  | 'Lingering Remnants'
  | 'Lost Worlds'
  | 'Love Through Ice'
  | 'Loyalty'
  | 'Lucky Connections'
  | 'Lucky Deck'
  | 'Luminous Trove'
  | "Lysah's Respite"
  | 'Magnum Opus'
  | 'Man With Bear'
  | 'Matryoshka'
  | 'Mawr Blaidd'
  | 'Merciless Armament'
  | 'Might is Right'
  | 'Misery in Darkness'
  | 'Mitts'
  | 'Monochrome'
  | 'More is Never Enough'
  | 'No Traces'
  | "Nook's Crown"
  | 'Parasitic Passengers'
  | 'Peaceful Moments'
  | 'Perfection'
  | 'Poisoned Faith'
  | 'Prejudice'
  | 'Pride Before the Fall'
  | 'Pride of the First Ones'
  | "Prometheus' Armoury"
  | 'Prosperity'
  | 'Rain Tempter'
  | 'Rain of Chaos'
  | 'Rats'
  | 'Rebirth'
  | 'Rebirth and Renewal'
  | 'Reckless Ambition'
  | 'Remembrance'
  | "Sambodhi's Vow"
  | "Sambodhi's Wisdom"
  | 'Scholar of the Seas'
  | 'Seven Years Bad Luck'
  | 'Shard of Fate'
  | 'Silence and Frost'
  | "Society's Remorse"
  | 'Something Dark'
  | 'Soul Quenched'
  | 'Struck by Lightning'
  | 'Succor of the Sinless'
  | 'Terrible Secret of Space'
  | 'The Academic'
  | 'The Admirer'
  | 'The Adventuring Spirit'
  | 'The Aesthete'
  | 'The Apothecary'
  | "The Archmage's Right Hand"
  | 'The Arena Champion'
  | 'The Army of Blood'
  | 'The Artist'
  | 'The Aspirant'
  | 'The Astromancer'
  | 'The Avenger'
  | 'The Awakened'
  | 'The Battle Born'
  | 'The Bear Woman'
  | 'The Beast'
  | 'The Betrayal'
  | 'The Bitter Blossom'
  | 'The Blazing Fire'
  | 'The Blessing of Moosh'
  | 'The Body'
  | 'The Bones'
  | 'The Brawny Battle Mage'
  | 'The Breach'
  | 'The Brittle Emperor'
  | 'The Cache'
  | 'The Cacophony'
  | 'The Calling'
  | 'The Card Sharp'
  | 'The Carrion Crow'
  | 'The Cartographer'
  | 'The Cataclysm'
  | 'The Catalyst'
  | 'The Catch'
  | 'The Celestial Justicar'
  | 'The Celestial Stone'
  | 'The Chains that Bind'
  | 'The Cheater'
  | 'The Chosen'
  | 'The Coming Storm'
  | 'The Conduit'
  | 'The Craving'
  | 'The Cursed King'
  | 'The Damned'
  | 'The Dapper Prodigy'
  | 'The Dark Mage'
  | 'The Darkest Dream'
  | 'The Deal'
  | 'The Deceiver'
  | 'The Deep Ones'
  | 'The Demon'
  | 'The Demoness'
  | 'The Destination'
  | 'The Doctor'
  | 'The Doppelganger'
  | 'The Dragon'
  | "The Dragon's Heart"
  | 'The Dreamer'
  | 'The Dreamland'
  | 'The Drunken Aristocrat'
  | 'The Dungeon Master'
  | 'The Easy Stroll'
  | 'The Eldritch Decay'
  | 'The Emptiness'
  | 'The Encroaching Darkness'
  | 'The Endless Darkness'
  | 'The Endurance'
  | 'The Enforcer'
  | 'The Enlightened'
  | 'The Enthusiasts'
  | 'The Escape'
  | 'The Eternal War'
  | 'The Ethereal'
  | 'The Explorer'
  | 'The Eye of Terror'
  | 'The Eye of the Dragon'
  | 'The Fathomless Depths'
  | 'The Feast'
  | 'The Fiend'
  | 'The Finishing Touch'
  | 'The Fishmonger'
  | 'The Fletcher'
  | "The Flora's Gift"
  | 'The Fool'
  | 'The Forgotten Treasure'
  | 'The Formless Sea'
  | 'The Forsaken'
  | 'The Fortunate'
  | 'The Forward Gaze'
  | 'The Fox'
  | 'The Fox in the Brambles'
  | 'The Gambler'
  | 'The Garish Power'
  | 'The Gemcutter'
  | 'The Gentleman'
  | 'The Gladiator'
  | 'The Golden Era'
  | 'The Greatest Intentions'
  | 'The Gulf'
  | 'The Hale Heart'
  | 'The Harvester'
  | 'The Hermit'
  | 'The Heroic Shot'
  | 'The Hive of Knowledge'
  | 'The Hoarder'
  | 'The Hook'
  | 'The Hunger'
  | 'The Immortal'
  | 'The Incantation'
  | 'The Innocent'
  | 'The Inoculated'
  | 'The Insane Cat'
  | 'The Insatiable'
  | 'The Inventor'
  | 'The Jester'
  | "The Jeweller's Boon"
  | 'The Journalist'
  | 'The Journey'
  | "The King's Blade"
  | "The King's Heart"
  | 'The Landing'
  | 'The Last One Standing'
  | 'The Last Supper'
  | 'The Leviathan'
  | 'The Lich'
  | 'The Life Thief'
  | 'The Lion'
  | 'The Long Con'
  | 'The Lord in Black'
  | 'The Lord of Celebration'
  | 'The Lover'
  | 'The Lunaris Priestess'
  | 'The Mad King'
  | 'The Magma Crab'
  | 'The Master'
  | 'The Master Artisan'
  | 'The Mercenary'
  | 'The Messenger'
  | "The Metalsmith's Gift"
  | "The Mind's Eyes"
  | 'The Mountain'
  | 'The Nurse'
  | 'The Oath'
  | 'The Obscured'
  | 'The Offering'
  | 'The Offspring'
  | 'The Old Man'
  | 'The One That Got Away'
  | 'The One With All'
  | 'The Opulent'
  | 'The Pack Leader'
  | 'The Pact'
  | 'The Patient'
  | 'The Penitent'
  | 'The Poet'
  | 'The Polymath'
  | 'The Porcupine'
  | 'The Price of Devotion'
  | 'The Price of Loyalty'
  | 'The Price of Prescience'
  | 'The Price of Protection'
  | 'The Primordial'
  | 'The Prince of Darkness'
  | 'The Professor'
  | 'The Progeny of Lunaris'
  | 'The Puzzle'
  | 'The Queen'
  | "The Rabbit's Foot"
  | 'The Rabid Rhoa'
  | 'The Realm'
  | 'The Return of the Rat'
  | 'The Risk'
  | 'The Rite of Elements'
  | 'The Road to Power'
  | 'The Rusted Bard'
  | 'The Ruthless Ceinture'
  | 'The Sacrifice'
  | "The Saint's Treasure"
  | "The Samurai's Eye"
  | 'The Scarred Meadow'
  | 'The Scavenger'
  | 'The Scholar'
  | 'The Scout'
  | 'The Seeker'
  | 'The Sephirot'
  | "The Shepherd's Sandals"
  | 'The Shieldbearer'
  | 'The Shortcut'
  | 'The Side Quest'
  | 'The Sigil'
  | 'The Siren'
  | 'The Skeleton'
  | 'The Soul'
  | 'The Spark and the Flame'
  | 'The Spoiled Prince'
  | 'The Standoff'
  | 'The Stormcaller'
  | 'The Strategist'
  | 'The Summoner'
  | 'The Sun'
  | 'The Surgeon'
  | 'The Surveyor'
  | 'The Survivalist'
  | "The Sword King's Salute"
  | 'The Thaumaturgist'
  | 'The Throne'
  | "The Tinkerer's Table"
  | 'The Tireless Extractor'
  | 'The Tower'
  | 'The Traitor'
  | 'The Transformation'
  | 'The Trial'
  | 'The Tumbleweed'
  | 'The Twilight Moon'
  | 'The Twins'
  | 'The Tyrant'
  | 'The Undaunted'
  | 'The Undisputed'
  | 'The Unexpected Prize'
  | 'The Union'
  | 'The Valkyrie'
  | 'The Vast'
  | 'The Visionary'
  | 'The Void'
  | 'The Warden'
  | 'The Warlord'
  | 'The Watcher'
  | 'The Web'
  | 'The Wedding Gift'
  | 'The White Knight'
  | 'The Whiteout'
  | 'The Wilted Rose'
  | 'The Wind'
  | 'The Witch'
  | 'The Wolf'
  | "The Wolf's Legacy"
  | "The Wolf's Shadow"
  | "The Wolven King's Bite"
  | 'The Wolverine'
  | 'The World Eater'
  | 'The Wrath'
  | 'The Wretched'
  | 'Thirst for Knowledge'
  | 'Three Faces in the Dark'
  | 'Three Voices'
  | 'Thunderous Skies'
  | 'Time-Lost Relic'
  | 'Tranquillity'
  | 'Treasure Hunter'
  | 'Triskaidekaphobia'
  | 'Turn the Other Cheek'
  | 'Unchained'
  | 'Underground Forest'
  | 'Unrequited Love'
  | 'Vanity'
  | 'Vile Power'
  | "Vinia's Token"
  | 'Void of the Elements'
  | 'Volatile Power'
  | 'Wealth and Power'
  | "Winter's Embrace"
  | 'Absolution'
  | 'Added Chaos Damage Support'
  | 'Added Cold Damage Support'
  | 'Added Fire Damage Support'
  | 'Added Lightning Damage Support'
  | 'Additional Accuracy Support'
  | 'Advanced Traps Support'
  | "Alchemist's Mark"
  | 'Ambush'
  | 'Ancestral Call Support'
  | 'Ancestral Cry'
  | 'Ancestral Protector'
  | 'Ancestral Warchief'
  | 'Anger'
  | 'Animate Guardian'
  | 'Animate Weapon'
  | 'Arc'
  | 'Arcane Cloak'
  | 'Arcane Surge Support'
  | 'Arcanist Brand'
  | 'Archmage Support'
  | 'Arctic Armour'
  | 'Armageddon Brand'
  | 'Arrogance Support'
  | 'Arrow Nova Support'
  | 'Artillery Ballista'
  | "Assassin's Mark"
  | 'Awakened Added Chaos Damage Support'
  | 'Awakened Added Cold Damage Support'
  | 'Awakened Added Fire Damage Support'
  | 'Awakened Added Lightning Damage Support'
  | 'Awakened Ancestral Call Support'
  | 'Awakened Arrow Nova Support'
  | 'Awakened Blasphemy Support'
  | 'Awakened Brutality Support'
  | 'Awakened Burning Damage Support'
  | 'Awakened Cast On Critical Strike Support'
  | 'Awakened Cold Penetration Support'
  | 'Awakened Controlled Destruction Support'
  | 'Awakened Deadly Ailments Support'
  | 'Awakened Elemental Focus Support'
  | 'Awakened Fire Penetration Support'
  | 'Awakened Hextouch Support'
  | 'Awakened Lightning Penetration Support'
  | 'Awakened Melee Physical Damage Support'
  | 'Awakened Melee Splash Support'
  | 'Awakened Minion Damage Support'
  | 'Awakened Vicious Projectiles Support'
  | 'Ball Lightning'
  | 'Ballista Totem Support'
  | 'Bane'
  | 'Barrage'
  | 'Barrage Support'
  | "Battlemage's Cry"
  | 'Bear Trap'
  | 'Behead Support'
  | 'Berserk'
  | 'Blade Blast'
  | 'Blade Flurry'
  | 'Blade Trap'
  | 'Blade Vortex'
  | 'Bladefall'
  | 'Bladestorm'
  | 'Blasphemy Support'
  | 'Blast Rain'
  | 'Blastchain Mine Support'
  | 'Blazing Salvo'
  | 'Blight'
  | 'Blind Support'
  | 'Blink Arrow'
  | 'Block Chance Reduction Support'
  | 'Blood Rage'
  | 'Blood and Sand'
  | 'Bloodlust Support'
  | 'Bloodthirst Support'
  | 'Bodyswap'
  | 'Bone Offering'
  | 'Bonechill Support'
  | 'Boneshatter'
  | 'Brand Recall'
  | 'Brutality Support'
  | 'Burning Arrow'
  | 'Burning Damage Support'
  | 'Cast On Critical Strike Support'
  | 'Cast on Death Support'
  | 'Cast on Melee Kill Support'
  | 'Cast when Damage Taken Support'
  | 'Cast when Stunned Support'
  | 'Cast while Channelling Support'
  | 'Caustic Arrow'
  | 'Chain Hook'
  | 'Chain Support'
  | 'Chance to Bleed Support'
  | 'Chance to Flee Support'
  | 'Chance to Poison Support'
  | 'Charged Dash'
  | 'Charged Mines Support'
  | 'Charged Traps Support'
  | 'Clarity'
  | 'Cleave'
  | 'Close Combat Support'
  | 'Cluster Traps Support'
  | 'Cobra Lash'
  | 'Cold Penetration Support'
  | 'Cold Snap'
  | 'Cold to Fire Support'
  | 'Combustion Support'
  | 'Concentrated Effect Support'
  | 'Conductivity'
  | 'Consecrated Path'
  | 'Contagion'
  | 'Controlled Blaze Support'
  | 'Controlled Destruction Support'
  | 'Conversion Trap'
  | 'Convocation'
  | 'Corrupting Cry Support'
  | 'Corrupting Fever'
  | 'Crackling Lance'
  | 'Creeping Frost'
  | 'Cremation'
  | 'Critical Strike Affliction Support'
  | 'Cruelty Support'
  | 'Culling Strike Support'
  | 'Cursed Ground Support'
  | 'Cyclone'
  | 'Damage on Full Life Support'
  | 'Dark Pact'
  | 'Dash'
  | 'Deadly Ailments Support'
  | 'Decay Support'
  | 'Decoy Totem'
  | 'Defiance Banner'
  | 'Desecrate'
  | 'Despair'
  | 'Destructive Link'
  | 'Determination'
  | 'Detonate Dead'
  | 'Detonate Mines'
  | 'Devour Support'
  | 'Devouring Totem'
  | 'Discharge'
  | 'Discipline'
  | 'Divine Blessing Support'
  | 'Divine Ire'
  | 'Dominating Blow'
  | 'Double Strike'
  | 'Dread Banner'
  | 'Dual Strike'
  | 'Earthbreaker Support'
  | 'Earthquake'
  | 'Earthshatter'
  | 'Efficacy Support'
  | 'Elemental Army Support'
  | 'Elemental Damage with Attacks Support'
  | 'Elemental Focus Support'
  | 'Elemental Hit'
  | 'Elemental Penetration Support'
  | 'Elemental Proliferation Support'
  | 'Elemental Weakness'
  | 'Empower Support'
  | 'Endurance Charge on Melee Stun Support'
  | 'Enduring Cry'
  | 'Energy Blade'
  | 'Energy Leech Support'
  | 'Enfeeble'
  | 'Enhance Support'
  | 'Enlighten Support'
  | 'Ensnaring Arrow'
  | 'Essence Drain'
  | 'Eternal Blessing Support'
  | 'Ethereal Knives'
  | 'Explosive Arrow'
  | 'Explosive Concoction'
  | 'Explosive Trap'
  | 'Exsanguinate'
  | 'Eye of Winter'
  | 'Faster Attacks Support'
  | 'Faster Casting Support'
  | 'Faster Projectiles Support'
  | 'Feeding Frenzy Support'
  | 'Fire Penetration Support'
  | 'Fire Trap'
  | 'Fireball'
  | 'Firestorm'
  | 'Fist of War Support'
  | 'Flame Dash'
  | 'Flame Link'
  | 'Flame Surge'
  | 'Flame Wall'
  | 'Flameblast'
  | 'Flamethrower Trap'
  | 'Flamewood Support'
  | 'Flammability'
  | 'Flesh Offering'
  | 'Flesh and Stone'
  | 'Flicker Strike'
  | 'Focused Ballista Support'
  | 'Forbidden Rite'
  | 'Fork Support'
  | 'Fortify Support'
  | 'Freezing Pulse'
  | 'Frenzy'
  | 'Fresh Meat Support'
  | 'Frigid Bond Support'
  | 'Frost Blades'
  | 'Frost Bomb'
  | 'Frost Shield'
  | 'Frost Wall'
  | 'Frostbite'
  | 'Frostblink'
  | 'Frostbolt'
  | 'Frozen Legion'
  | 'Galvanic Arrow'
  | 'Galvanic Field'
  | "General's Cry"
  | 'Generosity Support'
  | 'Glacial Cascade'
  | 'Glacial Hammer'
  | 'Grace'
  | 'Greater Multiple Projectiles Support'
  | 'Greater Volley Support'
  | 'Ground Slam'
  | "Guardian's Blessing Support"
  | 'Haste'
  | 'Hatred'
  | 'Heavy Strike'
  | 'Herald of Agony'
  | 'Herald of Ash'
  | 'Herald of Ice'
  | 'Herald of Purity'
  | 'Herald of Thunder'
  | 'Hex Bloom Support'
  | 'Hexblast'
  | 'Hextouch Support'
  | 'High-Impact Mine Support'
  | 'Holy Flame Totem'
  | 'Hydrosphere'
  | 'Hypothermia Support'
  | 'Ice Bite Support'
  | 'Ice Crash'
  | 'Ice Nova'
  | 'Ice Shot'
  | 'Ice Spear'
  | 'Ice Trap'
  | 'Icicle Mine'
  | 'Ignite Proliferation Support'
  | 'Immolate Support'
  | 'Immortal Call'
  | 'Impale Support'
  | 'Impending Doom Support'
  | 'Incinerate'
  | 'Increased Area of Effect Support'
  | 'Increased Critical Damage Support'
  | 'Increased Critical Strikes Support'
  | 'Increased Duration Support'
  | 'Infernal Blow'
  | 'Infernal Cry'
  | 'Infernal Legion Support'
  | 'Infused Channelling Support'
  | 'Innervate Support'
  | 'Inspiration Support'
  | 'Intensify Support'
  | 'Intimidating Cry'
  | 'Intuitive Link'
  | 'Iron Grip Support'
  | 'Iron Will Support'
  | 'Item Quantity Support'
  | 'Item Rarity Support'
  | 'Kinetic Blast'
  | 'Kinetic Bolt'
  | 'Knockback Support'
  | 'Lacerate'
  | 'Lancing Steel'
  | 'Leap Slam'
  | 'Less Duration Support'
  | 'Lesser Multiple Projectiles Support'
  | 'Life Gain on Hit Support'
  | 'Life Leech Support'
  | 'Lifetap Support'
  | 'Lightning Arrow'
  | 'Lightning Conduit'
  | 'Lightning Penetration Support'
  | 'Lightning Spire Trap'
  | 'Lightning Strike'
  | 'Lightning Tendrils'
  | 'Lightning Trap'
  | 'Lightning Warp'
  | 'Locus Mine Support'
  | 'Maim Support'
  | 'Malevolence'
  | 'Mana Leech Support'
  | 'Manabond'
  | 'Manaforged Arrows Support'
  | 'Mark On Hit Support'
  | 'Meat Shield Support'
  | 'Melee Physical Damage Support'
  | 'Melee Splash Support'
  | 'Minefield Support'
  | 'Minion Damage Support'
  | 'Minion Life Support'
  | 'Minion Speed Support'
  | 'Mirage Archer Support'
  | 'Mirror Arrow'
  | 'Molten Shell'
  | 'Molten Strike'
  | 'Momentum Support'
  | 'Multiple Totems Support'
  | 'Multiple Traps Support'
  | 'Multistrike Support'
  | 'Nightblade Support'
  | 'Orb of Storms'
  | 'Overcharge Support'
  | 'Penance Brand'
  | 'Perforate'
  | 'Pestilent Strike'
  | 'Petrified Blood'
  | 'Phase Run'
  | 'Physical to Lightning Support'
  | 'Pierce Support'
  | 'Pinpoint Support'
  | 'Plague Bearer'
  | "Poacher's Mark"
  | 'Point Blank Support'
  | 'Poisonous Concoction'
  | 'Portal'
  | 'Power Charge On Critical Support'
  | 'Power Siphon'
  | 'Precision'
  | 'Predator Support'
  | 'Pride'
  | 'Prismatic Burst Support'
  | 'Protective Link'
  | 'Pulverise Support'
  | 'Puncture'
  | 'Punishment'
  | 'Purifying Flame'
  | 'Purity of Elements'
  | 'Purity of Fire'
  | 'Purity of Ice'
  | 'Purity of Lightning'
  | 'Pyroclast Mine'
  | 'Rage Support'
  | 'Rage Vortex'
  | 'Rain of Arrows'
  | 'Raise Spectre'
  | 'Raise Zombie'
  | 'Rallying Cry'
  | 'Reap'
  | 'Reave'
  | 'Reckoning'
  | 'Rejuvenation Totem'
  | 'Returning Projectiles Support'
  | 'Righteous Fire'
  | 'Riposte'
  | 'Rolling Magma'
  | 'Ruthless Support'
  | 'Sacrifice Support'
  | 'Sadism Support'
  | 'Scorching Ray'
  | 'Scourge Arrow'
  | 'Searing Bond'
  | 'Second Wind Support'
  | 'Seismic Cry'
  | 'Seismic Trap'
  | 'Shattering Steel'
  | 'Shield Charge'
  | 'Shield Crush'
  | 'Shock Nova'
  | 'Shockwave Support'
  | 'Shockwave Totem'
  | 'Shrapnel Ballista'
  | 'Siege Ballista'
  | 'Sigil of Power'
  | 'Siphoning Trap'
  | 'Slower Projectiles Support'
  | 'Smite'
  | 'Smoke Mine'
  | 'Snipe'
  | "Sniper's Mark"
  | 'Soul Link'
  | 'Soulrend'
  | 'Spark'
  | 'Spectral Helix'
  | 'Spectral Shield Throw'
  | 'Spectral Throw'
  | 'Spell Cascade Support'
  | 'Spell Echo Support'
  | 'Spell Totem Support'
  | 'Spellblade Support'
  | 'Spellslinger'
  | 'Spirit Offering'
  | 'Split Arrow'
  | 'Splitting Steel'
  | 'Static Strike'
  | 'Steelskin'
  | 'Storm Brand'
  | 'Storm Burst'
  | 'Storm Call'
  | 'Storm Rain'
  | 'Stormbind'
  | 'Stormblast Mine'
  | 'Stun Support'
  | 'Summon Carrion Golem'
  | 'Summon Chaos Golem'
  | 'Summon Flame Golem'
  | 'Summon Holy Relic'
  | 'Summon Ice Golem'
  | 'Summon Lightning Golem'
  | 'Summon Phantasm Support'
  | 'Summon Raging Spirit'
  | 'Summon Reaper'
  | 'Summon Skeletons'
  | 'Summon Skitterbots'
  | 'Summon Stone Golem'
  | 'Sunder'
  | 'Sweep'
  | 'Swift Affliction Support'
  | 'Swift Assembly Support'
  | 'Swiftbrand Support'
  | 'Tectonic Slam'
  | 'Tempest Shield'
  | 'Temporal Chains'
  | 'Temporal Rift'
  | 'Tornado'
  | 'Tornado Shot'
  | 'Toxic Rain'
  | 'Trap Support'
  | 'Trap and Mine Damage Support'
  | 'Trauma Support'
  | 'Trinity Support'
  | 'Unbound Ailments Support'
  | 'Unearth'
  | 'Unleash Support'
  | 'Urgent Orders Support'
  | 'Vaal Absolution'
  | 'Vaal Ancestral Warchief'
  | 'Vaal Animate Weapon'
  | 'Vaal Arc'
  | 'Vaal Arctic Armour'
  | 'Vaal Blade Flurry'
  | 'Vaal Blade Vortex'
  | 'Vaal Blight'
  | 'Vaal Breach'
  | 'Vaal Burning Arrow'
  | 'Vaal Caustic Arrow'
  | 'Vaal Clarity'
  | 'Vaal Cleave'
  | 'Vaal Cold Snap'
  | 'Vaal Cyclone'
  | 'Vaal Detonate Dead'
  | 'Vaal Discipline'
  | 'Vaal Domination'
  | 'Vaal Double Strike'
  | 'Vaal Earthquake'
  | 'Vaal Fireball'
  | 'Vaal Firestorm'
  | 'Vaal Flameblast'
  | 'Vaal Flicker Strike'
  | 'Vaal Glacial Hammer'
  | 'Vaal Grace'
  | 'Vaal Ground Slam'
  | 'Vaal Haste'
  | 'Vaal Ice Nova'
  | 'Vaal Ice Shot'
  | 'Vaal Immortal Call'
  | 'Vaal Impurity of Fire'
  | 'Vaal Impurity of Ice'
  | 'Vaal Impurity of Lightning'
  | 'Vaal Lightning Arrow'
  | 'Vaal Lightning Strike'
  | 'Vaal Lightning Trap'
  | 'Vaal Lightning Warp'
  | 'Vaal Molten Shell'
  | 'Vaal Molten Strike'
  | 'Vaal Power Siphon'
  | 'Vaal Rain of Arrows'
  | 'Vaal Reap'
  | 'Vaal Reave'
  | 'Vaal Rejuvenation Totem'
  | 'Vaal Righteous Fire'
  | 'Vaal Smite'
  | 'Vaal Spark'
  | 'Vaal Spectral Throw'
  | 'Vaal Storm Call'
  | 'Vaal Summon Skeletons'
  | 'Vaal Venom Gyre'
  | 'Vaal Volcanic Fissure'
  | 'Vampiric Link'
  | 'Vengeance'
  | 'Venom Gyre'
  | 'Vicious Projectiles Support'
  | 'Vigilant Strike'
  | 'Vile Toxins Support'
  | 'Viper Strike'
  | 'Vitality'
  | 'Void Manipulation Support'
  | 'Void Sphere'
  | 'Volatile Dead'
  | 'Volatility Support'
  | 'Volcanic Fissure'
  | 'Volley Support'
  | 'Voltaxic Burst'
  | 'Vortex'
  | 'Vulnerability'
  | 'War Banner'
  | "Warlord's Mark"
  | 'Wave of Conviction'
  | 'Whirling Blades'
  | 'Wild Strike'
  | 'Winter Orb'
  | 'Wintertide Brand'
  | 'Wither'
  | 'Withering Step'
  | 'Withering Touch Support'
  | 'Wrath'
  | 'Zealotry'  | 'Gilded Abyss Scarab'
  | 'Gilded Ambush Scarab'
  | 'Gilded Bestiary Scarab'
  | 'Gilded Blight Scarab'
  | 'Gilded Breach Scarab'
  | 'Gilded Cartography Scarab'
  | 'Gilded Divination Scarab'
  | 'Gilded Elder Scarab'
  | 'Gilded Expedition Scarab'
  | 'Gilded Harbinger Scarab'
  | 'Gilded Legion Scarab'
  | 'Gilded Ultimatum Scarab'
  | 'Gilded Reliquary Scarab'
  | 'Gilded Shaper Scarab'
  | 'Gilded Sulphite Scarab'
  | 'Gilded Torment Scarab'
  | 'Polished Abyss Scarab'
  | 'Polished Ambush Scarab'
  | 'Polished Bestiary Scarab'
  | 'Polished Blight Scarab'
  | 'Polished Breach Scarab'
  | 'Polished Cartography Scarab'
  | 'Polished Divination Scarab'
  | 'Polished Elder Scarab'
  | 'Polished Expedition Scarab'
  | 'Polished Harbinger Scarab'
  | 'Polished Legion Scarab'
  | 'Polished Ultimatum Scarab'
  | 'Polished Reliquary Scarab'
  | 'Polished Shaper Scarab'
  | 'Polished Sulphite Scarab'
  | 'Polished Torment Scarab'
  | 'Rusted Abyss Scarab'
  | 'Rusted Ambush Scarab'
  | 'Rusted Bestiary Scarab'
  | 'Rusted Blight Scarab'
  | 'Rusted Breach Scarab'
  | 'Rusted Cartography Scarab'
  | 'Rusted Divination Scarab'
  | 'Rusted Elder Scarab'
  | 'Rusted Expedition Scarab'
  | 'Rusted Harbinger Scarab'
  | 'Rusted Legion Scarab'
  | 'Rusted Ultimatum Scarab'
  | 'Rusted Reliquary Scarab'
  | 'Rusted Shaper Scarab'
  | 'Rusted Sulphite Scarab'
  | 'Rusted Torment Scarab'
  | 'Winged Abyss Scarab'
  | 'Winged Ambush Scarab'
  | 'Winged Bestiary Scarab'
  | 'Winged Blight Scarab'
  | 'Winged Breach Scarab'
  | 'Winged Cartography Scarab'
  | 'Winged Divination Scarab'
  | 'Winged Elder Scarab'
  | 'Winged Expedition Scarab'
  | 'Winged Harbinger Scarab'
  | 'Winged Legion Scarab'
  | 'Winged Ultimatum Scarab'
  | 'Winged Reliquary Scarab'
  | 'Winged Shaper Scarab'
  | 'Winged Sulphite Scarab'
  | 'Winged Torment Scarab'
  | "Rogue's Marker"
  | "Al-Hezmin's Crest"
  | "Baran's Crest"
  | 'Blood-filled Vessel'
  | 'Dedication to the Goddess'
  | 'Divine Vessel'
  | "Drox's Crest"
  | 'Fragment of Constriction'
  | 'Fragment of Emptiness'
  | 'Fragment of Enslavement'
  | 'Fragment of Eradication'
  | 'Fragment of Knowledge'
  | 'Fragment of Purification'
  | 'Fragment of Shape'
  | 'Fragment of Terror'
  | 'Fragment of the Chimera'
  | 'Fragment of the Hydra'
  | 'Fragment of the Minotaur'
  | 'Fragment of the Phoenix'
  | 'Gift to the Goddess'
  | 'Mortal Grief'
  | 'Mortal Hope'
  | 'Mortal Ignorance'
  | 'Mortal Rage'
  | 'Offering to the Goddess'
  | 'Sacred Blossom'
  | 'Sacrifice at Dawn'
  | 'Sacrifice at Dusk'
  | 'Sacrifice at Midnight'
  | 'Sacrifice at Noon'
  | 'Simulacrum'
  | "The Maven's Writ"
  | 'Timeless Eternal Emblem'
  | 'Timeless Karui Emblem'
  | 'Timeless Maraketh Emblem'
  | 'Timeless Templar Emblem'
  | 'Timeless Vaal Emblem'
  | 'Tribute to the Goddess'
  | 'Unrelenting Timeless Eternal Emblem'
  | 'Unrelenting Timeless Karui Emblem'
  | 'Unrelenting Timeless Maraketh Emblem'
  | 'Unrelenting Timeless Templar Emblem'
  | 'Unrelenting Timeless Vaal Emblem'
  | "Veritania's Crest"
  | "Goat's Horn"
  | "Rusted Axe"
