export type Currency =
  | 'Abrasive Catalyst'
  | 'Accelerating Catalyst'
  | 'Albino Rhoa Feather'
  | 'Alchemy Shard'
  | 'Alteration Shard'
  | 'Ancient Orb'
  | 'Ancient Shard'
  | 'Annulment Shard'
  | "Armourer's Scrap"
  | 'Astragali'
  | 'Awakened Sextant'
  | "Awakener's Orb"
  | 'Bestiary Orb'
  | 'Binding Shard'
  | "Blacksmith's Whetstone"
  | 'Blessed Orb'
  | 'Blessing of Chayula'
  | 'Blessing of Esh'
  | 'Blessing of Tul'
  | 'Blessing of Uul-Netol'
  | 'Blessing of Xoph'
  | 'Blighted Scouting Report'
  | 'Burial Medallion'
  | "Cartographer's Chisel"
  | 'Chaos Orb'
  | 'Chaos Shard'
  | 'Charged Compass'
  | 'Chromatic Orb'
  | 'Comprehensive Scouting Report'
  | 'Crescent Splinter'
  | "Crusader's Exalted Orb"
  | 'Delirious Scouting Report'
  | 'Divine Orb'
  | 'Eldritch Chaos Orb'
  | 'Eldritch Exalted Orb'
  | 'Eldritch Orb of Annulment'
  | 'Elevated Sextant'
  | "Engineer's Orb"
  | "Engineer's Shard"
  | 'Enkindling Orb'
  | 'Eternal Orb'
  | 'Exalted Orb'
  | 'Exalted Shard'
  | 'Exceptional Eldritch Ember'
  | 'Exceptional Eldritch Ichor'
  | 'Exotic Coinage'
  | "Explorer's Scouting Report"
  | "Facetor's Lens"
  | 'Fertile Catalyst'
  | 'Fracturing Orb'
  | 'Fracturing Shard'
  | "Gemcutter's Prism"
  | "Glassblower's Bauble"
  | 'Grand Eldritch Ember'
  | 'Grand Eldritch Ichor'
  | 'Greater Eldritch Ember'
  | 'Greater Eldritch Ichor'
  | "Harbinger's Orb"
  | "Harbinger's Shard"
  | 'Horizon Shard'
  | "Hunter's Exalted Orb"
  | 'Imbued Catalyst'
  | 'Influenced Scouting Report'
  | 'Instilling Orb'
  | 'Intrinsic Catalyst'
  | "Jeweller's Orb"
  | 'Lesser Eldritch Ember'
  | 'Lesser Eldritch Ichor'
  | 'Mirror Shard'
  | 'Mirror of Kalandra'
  | 'Noxious Catalyst'
  | 'Oil Extractor'
  | "Operative's Scouting Report"
  | 'Orb of Alchemy'
  | 'Orb of Alteration'
  | 'Orb of Annulment'
  | 'Orb of Augmentation'
  | 'Orb of Binding'
  | 'Orb of Chance'
  | 'Orb of Conflict'
  | 'Orb of Dominance'
  | 'Orb of Fusing'
  | 'Orb of Horizons'
  | 'Orb of Regret'
  | 'Orb of Scouring'
  | 'Orb of Transmutation'
  | 'Orb of Unmaking'
  | 'Otherworldly Scouting Report'
  | 'Portal Scroll'
  | 'Primal Crystallised Lifeforce'
  | 'Prime Regrading Lens'
  | 'Prismatic Catalyst'
  | "Redeemer's Exalted Orb"
  | 'Regal Orb'
  | 'Regal Shard'
  | 'Ritual Splinter'
  | 'Ritual Vessel'
  | 'Sacred Crystallised Lifeforce'
  | 'Sacred Orb'
  | 'Scrap Metal'
  | 'Scroll of Wisdom'
  | 'Secondary Regrading Lens'
  | 'Singular Scouting Report'
  | 'Stacked Deck'
  | "Surveyor's Compass"
  | 'Tailoring Orb'
  | "Tainted Armourer's Scrap"
  | "Tainted Blacksmith's Whetstone"
  | 'Tainted Blessing'
  | 'Tainted Chaos Orb'
  | 'Tainted Chromatic Orb'
  | 'Tainted Divine Teardrop'
  | 'Tainted Exalted Orb'
  | "Tainted Jeweller's Orb"
  | 'Tainted Mythic Orb'
  | 'Tainted Orb of Fusing'
  | 'Tempering Catalyst'
  | 'Tempering Orb'
  | 'Transmutation Shard'
  | 'Turbulent Catalyst'
  | 'Unstable Catalyst'
  | 'Vaal Orb'
  | 'Vaal Scouting Report'
  | 'Veiled Orb'
  | 'Vivid Crystallised Lifeforce'
  | "Warlord's Exalted Orb"
  | 'Wild Crystallised Lifeforce'
  | "Hinekora's Lock"
