export type Fragments =
  | "Al-Hezmin's Crest"
  | "Baran's Crest"
  | 'Blood-filled Vessel'
  | 'Dedication to the Goddess'
  | 'Divine Vessel'
  | "Drox's Crest"
  | 'Fragment of Constriction'
  | 'Fragment of Emptiness'
  | 'Fragment of Enslavement'
  | 'Fragment of Eradication'
  | 'Fragment of Knowledge'
  | 'Fragment of Purification'
  | 'Fragment of Shape'
  | 'Fragment of Terror'
  | 'Fragment of the Chimera'
  | 'Fragment of the Hydra'
  | 'Fragment of the Minotaur'
  | 'Fragment of the Phoenix'
  | 'Gift to the Goddess'
  | 'Mortal Grief'
  | 'Mortal Hope'
  | 'Mortal Ignorance'
  | 'Mortal Rage'
  | 'Offering to the Goddess'
  | 'Sacred Blossom'
  | 'Sacrifice at Dawn'
  | 'Sacrifice at Dusk'
  | 'Sacrifice at Midnight'
  | 'Sacrifice at Noon'
  | 'Simulacrum'
  | "The Maven's Writ"
  | 'Timeless Eternal Emblem'
  | 'Timeless Karui Emblem'
  | 'Timeless Maraketh Emblem'
  | 'Timeless Templar Emblem'
  | 'Timeless Vaal Emblem'
  | 'Tribute to the Goddess'
  | 'Unrelenting Timeless Eternal Emblem'
  | 'Unrelenting Timeless Karui Emblem'
  | 'Unrelenting Timeless Maraketh Emblem'
  | 'Unrelenting Timeless Templar Emblem'
  | 'Unrelenting Timeless Vaal Emblem'
  | "Veritania's Crest"
