export type ItemClass =
  | 'Gloves'
  | 'Incursion Items'
  | 'Mana Flasks'
  | 'One Hand Axes'
  | 'Quest Items'
  | 'Delve Stackable Socketable Currency'
  | 'Memories'
  | 'Microtransactions'
  | 'Claws'
  | 'Body Armours'
  | 'Blueprints'
  | 'Contracts'
  | 'Atlas Upgrade Items'
  | 'Heist Cloaks'
  | 'Rings'
  | 'Maps'
  | 'Misc Map Items'
  | 'Thrusting One Hand Swords'
  | 'Staves'
  | 'Metamorph Samples'
  | 'Divination Cards'
  | 'Quivers'
  | 'Sanctified Relics'
  | 'One Hand Swords'
  | 'Map Fragments'
  | 'Life Flasks'
  | 'Bows'
  | 'Heist Tools'
  | 'Two Hand Swords'
  | 'Amulets'
  | 'Two Hand Maces'
  | 'Vault Keys'
  | 'Two Hand Axes'
  | 'Sanctum Research'
  | 'Relics'
  | 'Sceptres'
  | 'Currency'
  | 'Sentinels'
  | 'Incubators'
  | 'Expedition Logbooks'
  | 'Pieces'
  | 'Trinkets'
  | 'Jewels'
  | 'Hybrid Flasks'
  | 'One Hand Maces'
  | 'Heist Brooches'
  | 'Skill Gems'
  | 'Breachstones'
  | 'Daggers'
  | 'Abyss Jewels'
  | 'Heist Gear'
  | 'Boots'
  | 'Rune Daggers'
  | 'Heist Targets'
  | 'Pantheon Souls'
  | 'Leaguestones'
  | 'Labyrinth Trinkets'
  | 'Support Gems'
  | 'Labyrinth Items'
  | 'Hideout Doodads'
  | 'Fishing Rods'
  | 'Utility Flasks'
  | 'Shields'
  | 'Helmets'
  | 'Warstaves'
  | 'Belts'
  | 'Wands'
  | "Flasks"
